<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['db_user'] = array(
					'dsn'	=> '',
					'hostname' => getenv('USER_DBHOSTNAME'),
					'username' => getenv('USER_DBUSERNAME'),
					'password' => getenv('USER_DBPASSWORD'),
					'database' => getenv('USER_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);

$config['db_fantasy'] = array(
					'dsn'	=> '',
					'hostname' => getenv('FANTASY_DBHOSTNAME'),
					'username' => getenv('FANTASY_DBUSERNAME'),
					'password' => getenv('FANTASY_DBPASSWORD'),
					'database' => getenv('FANTASY_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);
			
$config['db_prediction'] = array(
					'dsn'	=> '',
					'hostname' => getenv('PREDICTION_DBHOSTNAME'),
					'username' => getenv('PREDICTION_DBUSERNAME'),
					'password' => getenv('PREDICTION_DBPASSWORD'),
					'database' => getenv('PREDICTION_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);

$config['db_open_predictor'] = array(
					'dsn'	=> '',
					'hostname' => getenv('OPEN_PREDICTOR_DBHOSTNAME'),
					'username' => getenv('OPEN_PREDICTOR_DBUSERNAME'),
					'password' => getenv('OPEN_PREDICTOR_DBPASSWORD'),
					'database' => getenv('OPEN_PREDICTOR_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);

$config['db_fixed_open_predictor'] = array(
					'dsn'	=> '',
					'hostname' => getenv('FIXED_OPEN_PREDICTOR_DBHOSTNAME'),
					'username' => getenv('FIXED_OPEN_PREDICTOR_DBUSERNAME'),
					'password' => getenv('FIXED_OPEN_PREDICTOR_DBPASSWORD'),
					'database' => getenv('FIXED_OPEN_PREDICTOR_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);


$config['db_admin_user'] = array(
					'dsn'	=> '',
					'hostname' => getenv('USER_DBHOSTNAME'),
					'username' => getenv('USER_DBUSERNAME'),
					'password' => getenv('USER_DBPASSWORD'),
					'database' => getenv('USER_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);

$config['db_admin_fantasy'] = array(
					'dsn'	=> '',
					'hostname' => getenv('FANTASY_DBHOSTNAME'),
					'username' => getenv('FANTASY_DBUSERNAME'),
					'password' => getenv('FANTASY_DBPASSWORD'),
					'database' => getenv('FANTASY_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);

$config['db_analytics'] = array(
				'dsn'	=> '',
				'hostname' => getenv('ANALYTIC_DBHOSTNAME'),
				'username' => getenv('ANALYTIC_DBUSERNAME'),
				'password' => getenv('ANALYTIC_DBPASSWORD'),
				'database' => getenv('ANALYTIC_DBNAME'),
				'dbdriver' => 'mysqli',
				'dbprefix' => 'vi_',
				'pconnect' => FALSE,
				'db_debug' => (ENVIRONMENT !== 'production'),
				'cache_on' => FALSE,
				'cachedir' => '',
				'char_set' => 'utf8',
				'dbcollat' => 'utf8_general_ci',
				'swap_pre' => '',
				'encrypt' => FALSE,
				'compress' => FALSE,
				'stricton' => FALSE,
				'failover' => array(),
				'save_queries' => (SAVE_QUERIES == 1)
			);			

$config['db_stock'] = array(
					'dsn'	=> '',	
					'hostname' => getenv('STOCK_DBHOSTNAME'),
					'username' => getenv('STOCK_DBUSERNAME'),
					'password' => getenv('STOCK_DBPASSWORD'),
					'database' => getenv('STOCK_DBNAME'),
					'dbdriver' => 'mysqli',
					'dbprefix' => 'vi_',
					'pconnect' => FALSE,
					'db_debug' => (ENVIRONMENT !== 'production'),
					'cache_on' => FALSE,
					'cachedir' => '',
					'char_set' => 'utf8',
					'dbcollat' => 'utf8_general_ci',
					'swap_pre' => '',
					'encrypt' => FALSE,
					'compress' => FALSE,
					'stricton' => FALSE,
					'failover' => array(),
					'save_queries' => (SAVE_QUERIES == 1)
				);	
