import { getImageBaseUrl } from "../Utilities/Utilities";
import app_config from "../InitialSetup/AppConfig";

const Images = {
    S3_BUCKET_IMG_PATH: app_config.s3.BUCKET + "assets/img/",
    TEAM_JERSY: getImageBaseUrl('jersy.png'),
    COIN: getImageBaseUrl('coins.png'),
    LOGO: getImageBaseUrl('logo.png'),
    TEAM_HYDERABAD: getImageBaseUrl('Hyderabad.png'),
    TEAM_KOLKATA: getImageBaseUrl('Kolkata.png'),
    NODATA: getImageBaseUrl('nodata.png'),
    ADD_CASE : getImageBaseUrl('add-cash-ic.svg'),
    REFERAL_BG:getImageBaseUrl('referal_prize_bg.png'),
    BANNER_REFER_FRIEND: getImageBaseUrl('ic_refer_friend.svg'),
    BANNER_ADD_FUND: getImageBaseUrl('ic_add_funds.svg'),
    CHARACTER: getImageBaseUrl('character.png'),
    FEATURED_RECT: getImageBaseUrl('featured-rectangle.png'),
    WINNING_ICON: getImageBaseUrl('winning-ic.png'),
    USERIMG: getImageBaseUrl('mark_zuckerberg.png'),
    DEFAULT_USER: getImageBaseUrl('default-user.png'),
    DEFAULT_AVATAR: getImageBaseUrl('default_avatar.svg'),
    INFO_ICON : getImageBaseUrl('ic-info-white.svg'),
    PAYMENT_METHOD: getImageBaseUrl('payment-method.png'),
    QUE_LOGO: getImageBaseUrl('que-logo.png'),
    ITEM1: getImageBaseUrl('item1.png'),
    ITEM2: getImageBaseUrl('item2.png'),
    ITEM3: getImageBaseUrl('item3.png'),
    ITEM4: getImageBaseUrl('item4.png'),
    ITEM5: getImageBaseUrl('item5.png'),
    VIDEO_IMG: getImageBaseUrl('video1.png'),
    VIDEO_BTN: getImageBaseUrl('video-btn.png'),
    PLAYER_GRAPH: getImageBaseUrl('player_graph.png'),
    MINUS_IMG: getImageBaseUrl('remove-ic@1x.svg'),
    PBL_PLAY: getImageBaseUrl('pbl-play.png'),
    MOBILE_IMG: getImageBaseUrl('mobile.png'),
    LOGO_PBL: getImageBaseUrl('logo.png'),
    LOGO_GRAY: getImageBaseUrl('logo-gray.png'),
    LOGO_VINFOTECH: getImageBaseUrl('vinfotech-logo.png'),
    GOOGLE_PLAY: getImageBaseUrl('google-play.png'),
    defaultPanImage: getImageBaseUrl('default_Pan_Image.png'),

    teams_ic: getImageBaseUrl('teams-ic.png'),
    trophy_ic: getImageBaseUrl('trophy-ic.png'),
    clock_ic: getImageBaseUrl('clock-ic.png'),
    no_data_bg_image: getImageBaseUrl('circle-shape-png-hd-background-view-all-images.png'),
    no_notification: getImageBaseUrl('no-notification.png'),
    no_data: getImageBaseUrl('no_data.jpg'),

    // BEANS: require('./../assets/img/beans.png'),

    pinned_ic: getImageBaseUrl('pinned-ic.png'),
    CAPTAION_IC: getImageBaseUrl('captain-ic.png'),
    VICE_CAPTAION_IC: getImageBaseUrl('vice-captain-ic.png'),
    NotePad: getImageBaseUrl('notepad.png'),
    GMAIL_LOGO: getImageBaseUrl('gmail logo.png'),
    GPLUS_LOGO: getImageBaseUrl('google-logo.png'),
    SIGNUP_BANNER: getImageBaseUrl('offer-banner.png'),
    WALLET_IMG: getImageBaseUrl('wallet.png'),
    BRAND_LOGO_FULL: getImageBaseUrl('brand-logo.svg'),
    BRAND_LOGO_FULL_PNG: getImageBaseUrl('brand-logo.png'),
    BRAND_LOGO: getImageBaseUrl('brand-logo-header.svg'),
    FIELD_VIEW_LOGO: getImageBaseUrl('FieldView-logo.svg'),
    WHITE_BRAND_LOGO: getImageBaseUrl('white-brand-logo-header.svg'),
    CRICKET_GROUND_BG: getImageBaseUrl('ground-cricket.svg'),
    VINFOTECH_BRAND: getImageBaseUrl('vinfotech-brand.png'),
    VINFOTECH_BRAND_WHITE: getImageBaseUrl('vinfotech-white-brand.png'),
    DEVELOPED_BY_LOGO: getImageBaseUrl('devloped-by-vinfotech.png'),
    HEADER_SHADOW: getImageBaseUrl('header-shadow.png'),
    NO_INTERNET: getImageBaseUrl('no-internet.svg'),
    BTN_ANDROID_APP: getImageBaseUrl('btn-android-app.png'),
    SPORTS_MAN: getImageBaseUrl('Sport-man.png'),
    COLLECTION_INFO: getImageBaseUrl('collection-img.jpg'),
    COLLECTION_TEXT_IMG: getImageBaseUrl('Collection.png'),
    MULTIGAME_INFO: getImageBaseUrl('collection-info.svg'),
    MULTIGAME_INFO_CREATE_TEAM_LOGO: getImageBaseUrl('tshirt-collection.svg'),
    WORLD_MAP: getImageBaseUrl('world-map.png'),
    // PLAY_STORE_BTN: getImageBaseUrl('appStore.png'),
    SOCIAL_NEWSFEED: getImageBaseUrl('social-newsfeed.png'),
    PBL_SCREEN: getImageBaseUrl('PBL_SCREEN.png'),
    FANTASY_SPORTS_GROUND: getImageBaseUrl('ground.png'),
    COUNTRY_FLAG: getImageBaseUrl('flag-ic.png'),
    LANGUAGE_IMG: getImageBaseUrl('language-img.png'),
    TICK_IC: getImageBaseUrl('tick-ic.svg'),
    PENDING_IC: getImageBaseUrl('pending-ic.svg'),
    BONUS_BANNER_BG: getImageBaseUrl('bonus-banner-bg.svg'),
    FAVOURITE: getImageBaseUrl('deal-badge-ic.svg'),
    CREDIT_IMG: getImageBaseUrl('credit-img.png'),
    PAYTM_IMG: getImageBaseUrl('Paytm_logo.png'),
    MOBILE_ICON: getImageBaseUrl('mobile-icon.svg'),
    MOBILE_ICON_WHITE: getImageBaseUrl('mobile-icon-white.svg'),
    EMAIL_ICON: getImageBaseUrl('email-icon.svg'),
    EMAIL_ICON_WHITE: getImageBaseUrl('email-icon-white.svg'),
    PAN_ICON: getImageBaseUrl('pancard-icon.svg'),
    PAN_ICON_PNG: getImageBaseUrl('pan-card-ic.png'),
    PAN_GRAY_ICON: getImageBaseUrl('pancard-icon-gray.svg'),
    BANK_ICON: getImageBaseUrl('bank-icon.svg'),
    BANK_ICON_WHITE: getImageBaseUrl('bank-icon-white.svg'),
    CARD_IMG: getImageBaseUrl('cards-img@2x.png'),
    ICON_G: getImageBaseUrl('featured.png'),
    ICON_M: getImageBaseUrl('multiple.png'),
    QUES_ICON: getImageBaseUrl('ques-ic.png'),
    REFER_FRIEND: getImageBaseUrl('refer-friends.png'),
    REFER_FRIEND_SM: getImageBaseUrl('refer-friends-sm.png'),
    SPORTS_HUB: getImageBaseUrl('Sports_Hub.png'),
    REFER_FRIEND_HEADER: getImageBaseUrl('refer_friend_header.png'),
    REFER_FRIEND_SIGNUP : getImageBaseUrl('ref-friend-signup-icon.png'),
    REFER_FRIEND_DEPOSIT : getImageBaseUrl('on-friend-deposit.png'),
    REFER_FRIEND_REWARD : getImageBaseUrl('loyalty-reward.png'),
    COPY_CODE : getImageBaseUrl('copy.png'),
    ZIG_LINE :  getImageBaseUrl('zig-line.png'),

    ZIG_ZAG_DOWN :  getImageBaseUrl('zig-zag-down.png'),

    DOT_LINE : getImageBaseUrl('dash-line-ln.png'),
    DOT_LINE_R : getImageBaseUrl('dash-line-ln-r.png'),
    REFER_IMG_SM : getImageBaseUrl('refer-img-sm.png'),
    COIN_SW1: getImageBaseUrl('1w-img.png'),
    COIN_SW2: getImageBaseUrl('2w-img.png'),
    COIN_SW3: getImageBaseUrl('3w-img.png'),
    W_IMG_COIN1: getImageBaseUrl('1w-img-coin.png'),
    W_IMG_COIN2: getImageBaseUrl('2w-img-coin.png'),
    W_IMG_COIN3: getImageBaseUrl('3w-img-coin.png'),
    SPIN_SW1: getImageBaseUrl('1w-spin.png'),
    SW1_ROOKIE: getImageBaseUrl('1w-rookie.png'),
    SPIN_SW2: getImageBaseUrl('2w-spin.png'),
    EARN_COINS: getImageBaseUrl('earn-coins.png'),
    SILVR_EARN_COINS: getImageBaseUrl('silver-earn-coins.png'),
    CHECKIN_TICK: getImageBaseUrl('checkin-tick.png'),
    IC_COIN: getImageBaseUrl('ic-coin.png'),
    IC_COIN_GRAY: getImageBaseUrl('ic-coin-gray.png'),
    CHECKIN_COIN_PERSON: getImageBaseUrl('ccp.png'),
    COINS_POPUP_SHAPE: getImageBaseUrl('coins-popup-shape.png'),
    FEEDBACK_IC: getImageBaseUrl('feedback-img-ic.png'),
    REFER_IC: getImageBaseUrl('refer-img1.png'),
    PROMOTION_IC: getImageBaseUrl('promotion-img-ic.png'),
    PREDICTION_IC: getImageBaseUrl('prediction-img-ic.png'),
    CARD_BACK_IMG_DETAIL: getImageBaseUrl('card-back-img-detail.png'),
    CHECKIN_IC: getImageBaseUrl('checkins-img-ic.png'),
    COIN_CM: getImageBaseUrl('coins-couchmark.png'),
    COIN_LINE: getImageBaseUrl('line-img.png'),
    COIN_BAG: getImageBaseUrl('mega_contest.png'),
    COINS_ON_WALLET: getImageBaseUrl('coins-on-my-wallet@3x.png'),
    SINGLE_LINE: getImageBaseUrl('line-single.png'),
    BG_SHAP: getImageBaseUrl('background-shap.png'),
    COINS_BACK_STRIPE: getImageBaseUrl('coins-back-stripe.png'),
    FB_THUMB: getImageBaseUrl('feedback-ic.svg'),
    NEW_FEATURE_IC: getImageBaseUrl('new-ic.svg'),
    REFER_LOCK : getImageBaseUrl('lock-circle-ic.svg'),
    DAILY : getImageBaseUrl('daily.png'),
    DFS_SHAPE_IMG : getImageBaseUrl('dfs-shape-img.png'),
    PRD_SHAPE_IMG : getImageBaseUrl('prd-shape-img.png'),
    PRD_IMG : getImageBaseUrl('prd-img.png'),
    PICKEM : getImageBaseUrl('pickem.png'),
    PREDICTION : getImageBaseUrl('prediction.png'),
    TOURNAMENT : getImageBaseUrl('tournament.png'),
    DELETE: getImageBaseUrl('delete.svg'),   
    SHUB_COUCHMARK : getImageBaseUrl('sportshub-couchmark.png'),
    PRE_CURVE : getImageBaseUrl('predictionn_curve.png'),
    PRD_PRIZE_IMG : getImageBaseUrl('prd-prize-img.png'),
    PRIZES_CAR : getImageBaseUrl('prizes-car.png'),
    TSHIRT_VS_IC : getImageBaseUrl('tshirt-vs-ic.png'),
    HELMET_IC : getImageBaseUrl('helmet-ic.png'),
    OPEN_PREDICTOR_BIG_IMG : getImageBaseUrl('open-predictor-img-big-img.png'),
    DAILY_BIG : getImageBaseUrl('daily-big.png'),
    PICKEM_BIG : getImageBaseUrl('pickem-big.png'),
    OPEN_PREDICTOR_NEW : getImageBaseUrl('open-predictor-new.png'),
    // NON_SPORTS_LABEL : getImageBaseUrl('non-Sports-label.svg'),

    LINK_COPY : getImageBaseUrl('link-ic.svg'),
    FACE_BOOK_ICON : getImageBaseUrl('fb-ic.svg'),
    SPECIAL_OFFER  : getImageBaseUrl('special-offer-label.png'), 
    THIN_ARROW  : getImageBaseUrl('arrow-thin-ic.svg'),
    THIN_ARROW_UP  : getImageBaseUrl('arrow-thin-ic-up.svg'), 
    OPEN_CARD_IMG_DETAIL  : getImageBaseUrl('dot-card-bg-img.png'), 
    ATTACHMENT_IC  : getImageBaseUrl('attchment-ic.svg'), 
    FIRST_RANK  : getImageBaseUrl('rank1.svg'), 
    SECOND_RANK  : getImageBaseUrl('rank2.svg'), 
    THIRD_RANK  : getImageBaseUrl('rank3.svg'), 
    AMAZON_IMG  : getImageBaseUrl('amazonimg.png'), 
    CONGRATS_IMG  : getImageBaseUrl('ribbon-bg-img.png'), 

    // Hall Of Fame F2P
    HALL_OF_FAME_BIG_ICON : getImageBaseUrl('hof-big-ic.png'),
    BG_HALL_OF_FAME : getImageBaseUrl('image_bg.png'),
    RIGHT_SHAPE : getImageBaseUrl('right_shape.png'),
    LEFT_SHAPE : getImageBaseUrl('left_shape.png'),
    HOF1 : getImageBaseUrl('hof-icon1.svg'),
    HOF2 : getImageBaseUrl('hof-icon2.svg'),
    HOF3 : getImageBaseUrl('hof-icon3.svg'),
    HALL_OF_FAME_SMALL_ICON :getImageBaseUrl('hof_small_icon.png'),
    IC_BONUS :getImageBaseUrl('bonus.png'),
    IC_INFO:getImageBaseUrl('ic-info.svg'),
    FOOTBALL_ICON : getImageBaseUrl('minileage_box.png'),
    STARS_ICON : getImageBaseUrl('stars.png'),
    IC1 : getImageBaseUrl('ic1.png'),
    IC2 : getImageBaseUrl('ic2.png'),
    IC3 : getImageBaseUrl('ic3.png'),
    IC4 : getImageBaseUrl('img.png'),
    PICK_EARNCOIN : getImageBaseUrl('pick-earncoin.jpg'),
    PREDICT_EARNCOIN : getImageBaseUrl('predict-earncoin.png'),
    PREDICT_LEARN : getImageBaseUrl('predict-learn.png'),
    DRAW_ICON : getImageBaseUrl('draw-icon.png'),
    PICKEM_HTP1 : getImageBaseUrl('pickemHTP1.png'),
    PICKEM_HTP2 : getImageBaseUrl('pickemHTP2.png'),
    PICKEM_HTP3 : getImageBaseUrl('pickemHTP3.png'),
    PICKEM_BANNER : getImageBaseUrl('Pickem-card-banner.png'),
    PICKEM_SHAPE_IMG : getImageBaseUrl('pickem-shape-img.png'),
    PICKEM_IMG : getImageBaseUrl('pickem-img.png'),
    BLUE_BG_IMG : getImageBaseUrl('blue-back-img.png'),
    DFS_BIG : getImageBaseUrl('DFS-big.png'),
    PICKEM_TOUR_IMG : getImageBaseUrl('pickem-tournament.jpg'),
    FTP_IMG : getImageBaseUrl('free-to-play.jpg'),
    MULTI_GAME_IMG : getImageBaseUrl('multi-game.jpg'),
    PRED_IMG : getImageBaseUrl('sport-prediction.jpg'),
    STOCK_FAN : getImageBaseUrl('stock-fantasy.jpg'),
    TOUR_MODE : getImageBaseUrl('tournament-mode.jpg'),
    MEN_IMG_REFER : getImageBaseUrl('men-img-refer.png'),
    EsportImg : getImageBaseUrl('EsportImg.png'),
    DFS_SIDE_IMG : getImageBaseUrl('daily-fantasy-side-Img.jpg'),
    OPEN_PRED_PP : getImageBaseUrl('open-predictor-prize-pool-Side.jpg'),
    OPEN_PRED_LEAD : getImageBaseUrl('open-predictor-leaderb-side-img.jpg'),
    USER_GROUP_IMG : getImageBaseUrl('user-grp-img.svg'),
    WAVE_IMG1 : getImageBaseUrl('wave1-image.jpg'),
    WAVE_IMG2 : getImageBaseUrl('wave2-image.jpg'),
    WAVE_IMG3 : getImageBaseUrl('wave3-image.jpg'),
    CONGO_MG_RIGHT : getImageBaseUrl('congo-img-right.jpg'),
    CONGO_MG_LEFT : getImageBaseUrl('congo-img-left.jpg'),

    // dark theme spcific images
    DT_COINS_POPUP_SHAPE: getImageBaseUrl('DT-coins-popup-shape.png'),
    DT_BRAND_LOGO_FULL: getImageBaseUrl('DT_brand-logo.svg'),
    DT_BRAND_LOGO_FULL_PNG: getImageBaseUrl('DT-brand-logo.png'),
    DT_BRAND_LOGO: getImageBaseUrl('DT-brand-logo-header.svg'),
    DT_SPORTS_HUB: getImageBaseUrl('DT_Sports_Hub.png'),
    DT_LINK_COPY : getImageBaseUrl('DT_link-ic.svg'),
    DT_FACE_BOOK_ICON : getImageBaseUrl('DT_fb-ic.svg'),
    DT_MOBILE_ICON: getImageBaseUrl('DT_mobile-icon.svg'),
    DT_MOBILE_ICON_WHITE: getImageBaseUrl('DT_mobile-icon-white.svg'),
    DT_EMAIL_ICON: getImageBaseUrl('DT_email-icon.svg'),
    DT_EMAIL_ICON_WHITE: getImageBaseUrl('DT_email-icon-white.svg'),
    DT_PAN_ICON: getImageBaseUrl('DT_pancard-icon.svg'),
    DT_PAN_GRAY_ICON: getImageBaseUrl('DT_pancard-icon-gray.svg'),
    DT_BANK_ICON: getImageBaseUrl('DT_bank-icon.svg'),
    DT_BANK_ICON_WHITE: getImageBaseUrl('DT_bank-icon-white.svg'),
    DT_COIN_SW1: getImageBaseUrl('DT_1w-img.png'),
    DT_COIN_SW2: getImageBaseUrl('DT_2w-img.png'),
    DT_COIN_SW3: getImageBaseUrl('DT_3w-img.png'),
    DT_ADD_CASE : getImageBaseUrl('DT_add-cash-ic.svg'),    
    DT_EARN_COINS: getImageBaseUrl('DT_earn-coins.png'),

    DT_PICKEM_TOUR_IMG : getImageBaseUrl('DT_pickem-tournament.png'),
    DT_FTP_IMG : getImageBaseUrl('DT_free-to-play.png'),
    DT_MULTI_GAME_IMG : getImageBaseUrl('DT_multi-game.png'),
    DT_OPEN_PRED_PP : getImageBaseUrl('DT_open-predictor-prize-pool-Side.png'),
    DT_OPEN_PRED_LEAD : getImageBaseUrl('DT_open-predictor-leaderb-side-img.png'),
    DT_WHITE_BRAND_LOGO: getImageBaseUrl('DT_white-brand-logo-header.svg'),
    DT_DFS_SIDE_IMG: getImageBaseUrl('DT_daily-fantasy-side-Img.png'),
    DT_PRED_IMG: getImageBaseUrl('DT_sport-prediction.png'),
    DT_MULTIGAME_INFO: getImageBaseUrl('collection-info.png'),
    DT_MULTIGAME_INFO_CREATE_TEAM_LOGO: getImageBaseUrl('tshirt-collection.png'),
    DT_CONGO_MG_RIGHT : getImageBaseUrl('DT_congo-img-right.png'),
    DT_CONGO_MG_LEFT : getImageBaseUrl('DT_congo-img-left.png'),
    DT_PICKEM_HTP1 : getImageBaseUrl('DT_pickemHTP1.png'),
    DT_PICKEM_HTP2 : getImageBaseUrl('DT_pickemHTP2.png'),
    DT_PICKEM_HTP3 : getImageBaseUrl('DT_pickemHTP3.png'),

    REFER_BANNER_IMG: getImageBaseUrl('RF-img.png'),
    REFER_BANNER_IMG_SM: getImageBaseUrl('RF-img-sm.png'),
    PLAY_PRED_BANNER_IMG: getImageBaseUrl('Play-Pred-img.png'),
    PLAY_PRED_BANNER_IMG2: getImageBaseUrl('Play-Pred-img-2.png'),
    // DFS_BANNER_IMG: getImageBaseUrl('dfs-player-img.png'),
    APPLE_STORE_LOGO : getImageBaseUrl('applestore-logo.png'),
    APPLE_APP_STORE : getImageBaseUrl('apple_app_store.png'),
    PRIVATE_CONTEST_BANNER : getImageBaseUrl('private-contest-group-banner.png'),
    PRIVATE_CONTEST_FRIENDS : getImageBaseUrl('friends-ic.svg'),
    PRIVATE_CONTEST_CHAT : getImageBaseUrl('chat-ic.svg'),
    PRIVATE_CONTEST_COMMISION : getImageBaseUrl('commision-ic.svg'),
    TRACKING : getImageBaseUrl('tracking.png'),
    PROMOTION : getImageBaseUrl('promotion.png'),
    INDUS_LEAD : getImageBaseUrl('indus_lead.png'),
    PRIVATE_CONTEST_SHARE_BG : getImageBaseUrl('ic_share_private_bg.png'),
    DOUBLE_LINE : getImageBaseUrl('duble-line.png'),
    DOWNLOAD_APP_BTN:getImageBaseUrl('download-app-btn.png'),
    COINIMG : getImageBaseUrl('coin-img.png'),
    ic_chat_unread : getImageBaseUrl('ic_chat_unread.png'),
    ic_chat : getImageBaseUrl('ic_chat.png'),
    PICKEM_TEAM_IMG1 : getImageBaseUrl('PickemTeamImg1.png'),
    PICKEM_TEAM_IMG2 : getImageBaseUrl('PickemTeamImg2.png'),
    RGM_IMG : getImageBaseUrl('RGM.png'),
    MUTE_CHAT: getImageBaseUrl('mute-ic.svg'),
    DOWNLOAD_APPSTORE_BTN:getImageBaseUrl('appstore.png'),
    DOWNLOAD_PLAYSTORE_BTN:getImageBaseUrl('playstore.png'),
    GROUP_WALLET:getImageBaseUrl('group_wallet.png'),
    PHONE_PAY:getImageBaseUrl('phone_pay.png'),
    AXIS:getImageBaseUrl('axis.png'),
    KOTAK:getImageBaseUrl('kotak.png'),
    HDFC:getImageBaseUrl('hdfc.png'),
    ICIC:getImageBaseUrl('icic.png'),
    SBI:getImageBaseUrl('sbi.png'),
    UPI:getImageBaseUrl('upi.png'),
    NET_BANKING:getImageBaseUrl('net_banking.png'),
    ZIG_ZAG_LINE:getImageBaseUrl('zig-zag-line.png'),
    REVERSE_FANTASY_ICON:getImageBaseUrl('reverse-fantasy-icon.png'),
    REVERSE_FANTASY_HTP:getImageBaseUrl('ReverseFantasyHTP.png'),
    RF_BANNER_IMG:getImageBaseUrl('RFBannerImg.png'),
    LEADERBOARD_IC:getImageBaseUrl('leaderboard-ic.svg'),
    PRIZES_IC:getImageBaseUrl('prizes-ic.svg'),
    DEFAULT_DFS_TOUR_IMG:getImageBaseUrl('DefaultDFSTourImg.png'),
    SCRATHC_COVER:getImageBaseUrl('scrathc_cover.png'),
    BRUSH:getImageBaseUrl('brush.png'),
    SCRATCH_SHAPE:getImageBaseUrl('scratch_shape.png'),
    TROPHY:getImageBaseUrl('trophy.png'),
    CELE:getImageBaseUrl('cele.png'),
    REFER_FRIEND_REWARD_COINS:getImageBaseUrl('loyalty-reward-coins.png'),
    XP_LEVEL:getImageBaseUrl('xplevel.png'),
    INCREASEL_EVEL:getImageBaseUrl('increaselevel.png'),
    EARN_LEVEL:getImageBaseUrl('earnlevel.png'),
    EARN_XPPOINTS:getImageBaseUrl('earnxppoints.png'),
    XP_INTRO_FOOTER:getImageBaseUrl('xp-intro-footer.png'),
    XP_BRONZE:getImageBaseUrl('xp-bronze.png'),
    XP_SILVER:getImageBaseUrl('xp-silver.png'),
    XP_GOLD:getImageBaseUrl('xp-gold.png'),
    XP_PLATINUM:getImageBaseUrl('xp-platinum.png'),
    XP_ELITE:getImageBaseUrl('xp-elite.png'),
    XP_DIAMOND:getImageBaseUrl('xp-diamond.png'),
    XP_DEFAULT_BADGE:getImageBaseUrl('xp-default-badge.png'),
    INTRODUCING_IMG:getImageBaseUrl('Introducing.png'),
    RFLB1:getImageBaseUrl('RFLB1.png'),
    RFLB2:getImageBaseUrl('RFLB2.png'),
    tb1:getImageBaseUrl('tb1.png'),
    tb2:getImageBaseUrl('tb2.png'),
    tb3:getImageBaseUrl('tb3.png'),
    stock_cal:getImageBaseUrl('stock_cal.png'),
    stock_mon:getImageBaseUrl('stock_mon.png'),
    stock_24:getImageBaseUrl('stock_24.png'),
    stock_img:getImageBaseUrl('stock_img.png'),
    daily_g:getImageBaseUrl('daily_g.png'),
    weekly_g:getImageBaseUrl('weekly_g.png'),
    monthly_g:getImageBaseUrl('monthly_g.png'),
    stock_hub:getImageBaseUrl('stock_hub.png'),
    search_dark:getImageBaseUrl('search_dark.png'),
    search_light:getImageBaseUrl('search_light.png'),
    
    BOOSTER_ICON :getImageBaseUrl('booster-icon.svg'),
    BOOSTER_STRAIGHT :getImageBaseUrl('booster-vertical.svg'),
    BOOSTER_NORMAL:getImageBaseUrl('booster-normal.png'),
    BOOSTER_ACTIVE:getImageBaseUrl('booster-active.png'),
    BOOSTER_DISABLE:getImageBaseUrl('booster-disable.png'),
    BOOSTER_DASH:getImageBaseUrl('dash-ic.svg'),
    AIRTEL_MONEY:getImageBaseUrl('airtel-money.png'),
    FREECHARGE:getImageBaseUrl('free-charge.png'),
    NO_BOOSTER:getImageBaseUrl('no-booster.png'),
    live:getImageBaseUrl('live.png'),
    dt_live:getImageBaseUrl('dt_live.png'),
    ROOKIE_LOGO:getImageBaseUrl('rookie_logo.png'),
    YOUR_ROOKIE:getImageBaseUrl('your_rookie.png'),
    DARK_YOUR_ROOKIE:getImageBaseUrl('dark_your_rookie.png'),
    ROOKIE_JOURNY:getImageBaseUrl('rookie_journy.png'),
    DARK_ROOKIE_JOURNY:getImageBaseUrl('dark_rookie_journy.png'),
    ROOKIE_ARROW:getImageBaseUrl('rookie_arrow.png'),
    ROOKIE_LINES:getImageBaseUrl('rookie_lines.png'),
    ROOKIE_WINNER:getImageBaseUrl('rookie_winner.png'),
    ROOKIE_WHATS:getImageBaseUrl('rookie_whats.png'),
    ROOKIE_STADIUM:getImageBaseUrl('rookie_stadium.png'),
    BENCH_INTO_IMG:getImageBaseUrl('bench-into-img.png'),
    TSHIT_WPLUS:getImageBaseUrl('gray-tshirt.png'),
    BENCH_IMG:getImageBaseUrl('benchImg.png'),
    ERROR_IC:getImageBaseUrl('error.png'),
    PL_LOGO:getImageBaseUrl('PL-logo.png'),
    REMOVE_ICON:getImageBaseUrl('minus-img.png'),
    REFRESH_ICON:getImageBaseUrl('refresh-icon.png'),
    BLANK_JERSY:getImageBaseUrl('ic-blank-tshirt.png'),
    UNDO:getImageBaseUrl('undo.png'),
    LOCK_PLAYER:getImageBaseUrl('lock-player.png'),
    REMOVE_PLAYER_ROSTER:getImageBaseUrl('remove-player-guru.png'),
    GENRATE_TEAM:getImageBaseUrl('genrate-team.png'),
    REFRESH_TEAM:getImageBaseUrl('refresh-team.png'),
    MANAGE_PLAYER:getImageBaseUrl('manage-player.png'),
    SAVE_LINEUP:getImageBaseUrl('save-lineup.png'),
    PL1:getImageBaseUrl('pl1.png'),
    PL2:getImageBaseUrl('pl2.png'),
    PL3:getImageBaseUrl('pl3.png'),
    PL4:getImageBaseUrl('pl4.png'),
    PL5:getImageBaseUrl('pl5.png'),
    REVERT:getImageBaseUrl('revert.svg'),
    STOCK_HTP1:getImageBaseUrl('stock-htp-step1.png'),
    STOCK_HTP2:getImageBaseUrl('stock-htp-step2.png'),
    STOCK_HTP3:getImageBaseUrl('stock-htp-step3.png'),
    STOCK_HTP4:getImageBaseUrl('stock-htp-step4.png'),
    LEADERBRD_TRPY:getImageBaseUrl('leaderboard-trophyImg.png'),   
    STOCK_EQU_HTP3:getImageBaseUrl('stock-equ-HTP-step3.png'),    
    PL_LOGO_SMALL:getImageBaseUrl('pl-logo-small.png'),
    STAGE_IMG:getImageBaseUrl('stageImg.png'),
    STK_EQ_LBY_BNR:getImageBaseUrl('stk-eq-bnr.png'),
    STK_ICICI_IMG:getImageBaseUrl('stock-icici.jpg'),
    QUIZ_BG:getImageBaseUrl('quizbg.png'),
    QUIZ_ICON:getImageBaseUrl('quizicon.png'),
    QUIZ_MG:getImageBaseUrl('quizmg.png'),
    OHNO_ICON:getImageBaseUrl('ohno.png'),
    CLAIM_BG:getImageBaseUrl('claimbg.jpg'),
    SPIN_EC:getImageBaseUrl('spin.png'),
    VIDEO_EC:getImageBaseUrl('video.png'),
    QUIZ_EC:getImageBaseUrl('quiz.png'),
    COMING_SOON:getImageBaseUrl('coming-soon.png'),
    COINS_BAG_IMG:getImageBaseUrl('coins-bag.png'),
    SPIN_BIGGER:getImageBaseUrl('spin-bigger.png'),
    SPIN_IC:getImageBaseUrl('spin-ic.png'),
    GOOD_LUCK_IMG:getImageBaseUrl('good-luck-img@2.png'),
    QZ_GRAY_GRAPH:getImageBaseUrl('gray-graph.png'),
    QZ_GRAY_XGRAPH:getImageBaseUrl('gray-xgraph.png'),
    QZ_GREEN_GRAPH:getImageBaseUrl('green-graph.png'),
    QZ_RED_GRAPH:getImageBaseUrl('red-graph.png'),
    TREASURE_BOX:getImageBaseUrl('treasure-box.png'),
    REFER_LOGO:getImageBaseUrl('refer-new-logo.png'),
    AFFILIATE_BANNER:getImageBaseUrl('affiliate-banner.png'),
    AFFILIATE_POPUP_BOTTOM:getImageBaseUrl('affiliate-bottom-popup.png'),
    AFFILIATE_POPUP_TOP:getImageBaseUrl('megaphoneA.png'),
    EMOJI_POPUP_TOP:getImageBaseUrl('emoji-aff.png'),
    AFFILIATE_DETAIL_TOP:getImageBaseUrl('affliate-detail-banner-top.png'),
    REFER_BOTTOM:getImageBaseUrl('refer-img-bottom.png'),   
    REFER_TOP:getImageBaseUrl('refer-img-top.png'),    
    DOWNLOAD_IMG:getImageBaseUrl('download-img-ic.png'),
    DOWNLOAD_MDL_IMG:getImageBaseUrl('download-app-mdl-img.png'),
    ANDROID_BTN_IMG:getImageBaseUrl('android-btn.png'),
    PLAY_StE_BTN_IMG:getImageBaseUrl('play-store-btn.png'),
    WON_SMILEY:getImageBaseUrl('smiley.png'),
    U_DID_IT:getImageBaseUrl('UDidIt.png'),
    COIN_WIN:getImageBaseUrl('coin-win.png'),
    GAME_CENTER:getImageBaseUrl('game-center.png'),
    GAME_CENTER_ROUND:getImageBaseUrl('game-center-icon.png'),
    PLAYED_PREDICTION:getImageBaseUrl('played-pre.png'),
    CONFIRM_PREDICTION:getImageBaseUrl('confirm-pre.jpg'),
    LIVE_GC:getImageBaseUrl('live.svg'),
    FLASH:getImageBaseUrl('flash.svg'),
    BAT_TEAM:getImageBaseUrl('bat.svg'),
    h2h_O:getImageBaseUrl('h2h-logo-orange.svg'),
    h2h_B:getImageBaseUrl('h2h-logo-orange.svg'),
    h2h_Y:getImageBaseUrl('h2h-logo-orange.svg'),
    h2h_W:getImageBaseUrl('h2h-logo-orange.svg'),
    USER_OPP:getImageBaseUrl('opp-user.png'),
    WHAT_IS_H2H:getImageBaseUrl('wih2h-image-bg.png'),
    WHAT_IS_H2H_ONE:getImageBaseUrl('wih2h-one.png'),
    WHAT_IS_H2H_TWO:getImageBaseUrl('wih2h-two.svg'),
    WHAT_IS_H2H_THREE:getImageBaseUrl('wih2h-three.png'),
    WHAT_IS_H2H_LOGO:getImageBaseUrl('header-h2h-logo.png'),
    CENTER_LEAD_IMG:getImageBaseUrl('center-lead-img.png'),
    LEAD_STEP1:getImageBaseUrl('lead-step1.png'),
    LEAD_STEP2:getImageBaseUrl('lead-step2.png'),
    LEAD_STEP3:getImageBaseUrl('lead-step3.png'),
    LEAD_STEP4:getImageBaseUrl('lead-step4.png'),
    LEAD_STEP_CIR1:getImageBaseUrl('lead-step-cir1.png'),
    LEAD_STEP_CIR2:getImageBaseUrl('lead-step-cir2.png'),
    LEAD_STEP_CIR3:getImageBaseUrl('lead-step-cir3.png'),
    LEAD_STEP_CIR4:getImageBaseUrl('lead-step-cir4.png'),
    MERCHANDISE_GIFT:getImageBaseUrl('merchandise-gift.svg'),
    STOCK_PREDICT_HTP1:getImageBaseUrl('stock-predict-htp-step1.png'),
    STOCK_PREDICT_HTP2:getImageBaseUrl('stock-predict-htp-step2.png'),
    STOCK_PREDICT_HTP3:getImageBaseUrl('stock-predict-htp-step3.png'),
    SMILY_SOCIAL:getImageBaseUrl('smily-social.png'),    
    BNB:getImageBaseUrl('BNB.png'),
    BNB_BSC:getImageBaseUrl('BNB.BSC.png'),
    ETH:getImageBaseUrl('ETH.png'),
    TRX:getImageBaseUrl('TRX.png'),
    C_ACCOUNT:getImageBaseUrl('crypto-accounts.png'),
    LF_WAITING_IMG:getImageBaseUrl('waiting-img3@2x.png'),
    S_ALERT_SUCC:getImageBaseUrl('alert-success@2x.png'),
    S_ALERT_DANG:getImageBaseUrl('alert-danger@2x.png'),
    BULB:getImageBaseUrl('bulb.png'),
    OVER_RESULT:getImageBaseUrl('over-result.svg'),
    WH2H_IMG1:getImageBaseUrl('challenge.svg'),
    WH2H_IMG2:getImageBaseUrl('wih2h-two.svg'),
    WH2H_IMG3:getImageBaseUrl('match.svg'),
    DFS_BANNER_SH:getImageBaseUrl('DFS-banner-SH.png'),
    STEQIMG:getImageBaseUrl('StEqImg.png'),
    STIMG:getImageBaseUrl('StImg.png'),
    STPRDIMG:getImageBaseUrl('StPrdImg.png'),
    LIVEFANIMG:getImageBaseUrl('LiveFanImg.png'),
    OPENPRDIMG:getImageBaseUrl('OpenPreImg.png'),
    OPENPRDLDRIMG:getImageBaseUrl('OpenPreLdrImg.png'),
    PRDWINIMG:getImageBaseUrl('PrdWinImg.png'),
    PICMIMG:getImageBaseUrl('PicmImg.png'),
    F2PIMG:getImageBaseUrl('F2PImg.png'),
    DAILYFANIMG:getImageBaseUrl('DFSImg.png'),
    LF_SUCCUSS:getImageBaseUrl('succuss.png'),
    LF_FAILED:getImageBaseUrl('failed.png'),
    LF_HTP1:getImageBaseUrl('LF_HTP1.png'),
    LF_HTP2:getImageBaseUrl('LF_HTP2.png'),
    LF_HTP3:getImageBaseUrl('LF_HTP3.png'),
    LF_HTP4:getImageBaseUrl('LF_HTP4.png'),
    LIVE_OVER_HEAD:getImageBaseUrl('live-over-head.svg'),
    MP3_ODDS:getImageBaseUrl('Signal.mp3'),
    REVERSE_ARROW_IMG:getImageBaseUrl('reverse-arrow-icon.png'),
    CHECK_MARK:getImageBaseUrl('check-mark.png'),
    ZIG_ZAG_BTM_RGT:getImageBaseUrl('zig-zag-btm-right.png'),
    MULTIGAME_IMG_IC:getImageBaseUrl('multigame-icon.svg'),
    STOCK_PREDICT_IMG:getImageBaseUrl('stock-predict.png'),
    STOCK_PREDICT_IMAGES1:getImageBaseUrl('stock-predict-img1.png'),
    STOCK_PREDICT_IMAGES2:getImageBaseUrl('stock-predict-img2.png'),
    STOCK_PREDICT_IMAGES3:getImageBaseUrl('stock-predict-img3.png'),
    STOCK_PREDICT_IMAGES4:getImageBaseUrl('stock-predict-img4.png'),
    STOCK_PREDICT_IMAGES5:getImageBaseUrl('stock-predict-img5.png'),
    STOCK_PREDICT_IMAGES6:getImageBaseUrl('stock-predict-img6.png'),
    STOCK_FANTASY_IMG1:getImageBaseUrl('stock_fantasy_img1.png'),
    STOCK_FANTASY_IMG2:getImageBaseUrl('stock_fantasy_img2.png'),
    STOCK_FANTASY_IMG3:getImageBaseUrl('stock_fantasy_img3.png'),
    STOCK_FANTASY_IMG4:getImageBaseUrl('stock_fantasy_img4.png'),
    STOCK_FANTASY_IMG5:getImageBaseUrl('stock_fantasy_img5.png'),
    STOCK_FANTASY_IMG6:getImageBaseUrl('stock_fantasy_img6.png'),
    STOCK_FANTASY_IMG7:getImageBaseUrl('stock_fantasy_img7.png'),
    DFS_IMG_1:getImageBaseUrl('DFS_img_1.png'),
    DFS_IMG_2:getImageBaseUrl('DFS_img_2.png'),
    DFS_IMG_3:getImageBaseUrl('DFS_img_3.png'),
    DFS_IMG_4:getImageBaseUrl('DFS_img_4.png'),
    DFS_IMG_5:getImageBaseUrl('DFS_img_5.png'),
    DFS_IMG_6:getImageBaseUrl('DFS_img_6.png'),
    PICKEM_IMG_1:getImageBaseUrl('pickem_img_1.png'),
    PICKEM_IMG_2:getImageBaseUrl('pickem_img_2.png'),
    PICKEM_IMG_3:getImageBaseUrl('pickem_img_3.png'),
    PICKEM_IMG_4:getImageBaseUrl('pickem_img_4.png'),
    PICKEM_IMG_5:getImageBaseUrl('pickem_img_5.png'),
    PREDICTOPOOL_IMG_1:getImageBaseUrl('PredictorPrizePool_img1.png'),
    PREDICTOPOOL_IMG_2:getImageBaseUrl('PredictorPrizePool_img2.png'),
    PREDICTOPOOL_IMG_3:getImageBaseUrl('PredictorPrizePool_img3.png'),
    PREDICTOPOOL_IMG_4:getImageBaseUrl('PredictorPrizePool_img4.png'),
    LIVE_STOCK_FANASY_IMG_1:getImageBaseUrl('LiveStockFantasy_img_1.png'),
    LIVE_STOCK_FANASY_IMG_2:getImageBaseUrl('LiveStockFantasy_img_2.png'),
    LIVE_STOCK_FANASY_IMG_3:getImageBaseUrl('LiveStockFantasy_img_3.png'),
    LIVE_STOCK_FANASY_IMG_4:getImageBaseUrl('LiveStockFantasy_img_4.png'),
    LIVE_STOCK_FANASY_IMG_5:getImageBaseUrl('LiveStockFantasy_img_5.png'),
    LIVE_STOCK_FANASY_IMG_6:getImageBaseUrl('LiveStockFantasy_img_6.png'),
    LIVE_STOCK_FANASY_IMG_7:getImageBaseUrl('LiveStockFantasy_img_7.png'),

    PICKS_FANTASY_IMG_1:getImageBaseUrl('picks_fantasy_img_1.png'),
    PICKS_FANTASY_IMG_2:getImageBaseUrl('picks_fantasy_img_2.png'),
    PICKS_FANTASY_IMG_3:getImageBaseUrl('picks_fantasy_img_3.png'),
    PICKS_FANTASY_IMG_4:getImageBaseUrl('picks_fantasy_img_4.png'),
    PICKS_FANTASY_IMG_5:getImageBaseUrl('picks_fantasy_img_5.png'),
    PICKS_FANTASY_IMG_6:getImageBaseUrl('picks_fantasy_img_6.png'),
    PERFECT_SCORE:getImageBaseUrl('perfect-score.svg'),
    GAME_CENTER_NODATA:getImageBaseUrl('nodata-game-center.png'),
    TOUR_TROPHY_IMG:getImageBaseUrl('trophy-tour.png'),
    PRIZE_BADGE_IMG:getImageBaseUrl('prize-badge-img.svg'),
    RANK_BADGE_IMG:getImageBaseUrl('rank-badge-img.svg'),
    DFS_TOUR_IMG_1:getImageBaseUrl('DFS_tour_htp1.png'),
    DFS_TOUR_IMG_2:getImageBaseUrl('DFS_tour_htp2.png'),
    DFS_TOUR_IMG_3:getImageBaseUrl('DFS_tour_htp3.png'),
    DFS_TOUR_IMG_4:getImageBaseUrl('DFS_tour_htp4.png'),
    DFS_TOUR_IMG_5:getImageBaseUrl('DFS_tour_htp5.png'),
    PICKEM_HTP_IMG1:getImageBaseUrl('HTPPickem1.png'), 
    PICKEM_HTP_IMG2:getImageBaseUrl('HTPPickem2.png'),
    PICKEM_HTP_IMG3:getImageBaseUrl('HTPPickem3.png'),
    PICKEM_HTP_IMG4:getImageBaseUrl('HTPPickem4.png'),
    PICKEM_HTP_IMG5:getImageBaseUrl('HTPPickem5.png'),
    REDEEM_BONUS_IMG:getImageBaseUrl('redeem-bonus-img.png'),
    REDEEM_CASH_IMG:getImageBaseUrl('redeem-cash-img.png'),
    REDEEM_LOCK_IMG:getImageBaseUrl('redeem-lock.svg'),
    DRAW_IMG:getImageBaseUrl('draw.svg'),
    LSF_CARD_GRAPH1:getImageBaseUrl('lsf-graph1.png'),
    LSF_CARD_GRAPH2:getImageBaseUrl('lsf-graph2.png'),
    LSF_CARD_GRAPH3:getImageBaseUrl('lsf-graph3.png'),
    TROPHY_IMG:getImageBaseUrl('trophy-img.png'),
    GAME_CENTER_CIRCLE:getImageBaseUrl('game-center-circle.svg'),
    ATTACHMENT_ICON:getImageBaseUrl('attchment-icon.svg'),
    QUIZ_IMG:getImageBaseUrl('quiz-img.png'),
    QUIZ_ICON_IMG:getImageBaseUrl('quiziconimg.png'),
    PERFECT_SCORE_IMG:getImageBaseUrl('perfect-score.png'),
    TOUR_CARD_IMG:getImageBaseUrl('tour-card-img.png'),
    PICKEM_JACKPORT:getImageBaseUrl('pickemJackport.png'),
    GEO_LOCATION:getImageBaseUrl('geo_location.png'),
    SAD:getImageBaseUrl('sad.png'),
    HAPPY:getImageBaseUrl('happy.png'),
    DOWN_ARROW:getImageBaseUrl('down-arrow.png'),
    ARROW_THREE:getImageBaseUrl('arw-three.svg'),
    GEO_LOCATION_IMG:getImageBaseUrl('geo-location.png'),
    BANNED_STATE:getImageBaseUrl('banned-state.png'),


    NO_DATA_SHADE:getImageBaseUrl('no-data-shade.png'),
    allow_dfs:getImageBaseUrl('allow_dfs.png'),
    allow_equity:getImageBaseUrl('allow_equity.png'),
    allow_fixed_open_predictor:getImageBaseUrl('allow_fixed_open_predictor.png'),
    allow_live_stock_fantasy:getImageBaseUrl('allow_live_stock_fantasy.png'),
    allow_open_predictor:getImageBaseUrl('allow_open_predictor.png'),
    pickem_tournament:getImageBaseUrl('allow_pickem_tournament.png'),
    allow_prediction:getImageBaseUrl('allow_prediction.png'),
    allow_stock_fantasy:getImageBaseUrl('allow_stock_fantasy.png'),
    allow_stock_predict:getImageBaseUrl('allow_stock_predict.png'),
    live_fantasy:getImageBaseUrl('live_fantasy.png'),
    picks_fantasy:getImageBaseUrl('picks_fantasy.png'),
    props_fantasy:getImageBaseUrl('props_fantasy.png'),
    earn_coin:getImageBaseUrl('earn_coin.png'),
    REDEEM_COIN_IMG:getImageBaseUrl('RedeemCoinImg.png'),
    REDEEM_CASH_IMG1:getImageBaseUrl('RedeemCashImg.png'),
    ROOKIE_CONTEST_IMG:getImageBaseUrl('rookie-contest-img.png'),
    ROOKIE_LINE_IMG:getImageBaseUrl('rookie-line-img.png'),
    ROOKIE_LINE_BG:getImageBaseUrl('rookie-contest-bg.png'),
    ROOKIE_ARROW_VIEW:getImageBaseUrl('rookie-arrow.png'),
    ROOKIE_POSITION_VIEW:getImageBaseUrl('rookie-position-img.png'),
    ROOKIE_CONTEST_VIEW:getImageBaseUrl('rookie-contest-view.png'),
    "tourgame_f1.png": getImageBaseUrl('f1.png'), 
    "tourgame_gp.png": getImageBaseUrl('gp.png'), 
    "tourgame_car.png": getImageBaseUrl('car.png'), 
    "tourgame_track.png": getImageBaseUrl('track.png'), 
    PL_NEW:getImageBaseUrl('pl-new.png'), 
    NO_DATA_VIEW:getImageBaseUrl('no-data-view.png'), 
    TROPHY_CUP_IMG:getImageBaseUrl('trophy-cup-img.png'), 
    HTP_LOUD_IMG:getImageBaseUrl('htp-loud-img.png'),
    TRACK_SVG:getImageBaseUrl('track.svg'), 
   
    BAHRAIN_INTERNATIONAL_CIRCUIT: getImageBaseUrl('BAHRAIN_INTERNATIONAL_CIRCUIT.svg'),
    JEDDAH_CORNICHE_CIRCUIT: getImageBaseUrl('JEDDAH_CORNICHE_CIRCUIT.svg'),
    MELBOURNE_GRAND_PRIX_CIRCUIT: getImageBaseUrl('MELBOURNE_GRAND_PRIX_CIRCUIT.svg'),
    BAKU_CITY_CIRCUIT: getImageBaseUrl('BAKU_CITY_CIRCUIT.svg'),
    MIAMI_INTERNATIONAL_AUTODROME: getImageBaseUrl('MIAMI_INTERNATIONAL_AUTODROME.svg'),
    AUTODROMO_ENZO_E_DINO_FERRARI: getImageBaseUrl('AUTODROMO_ENZO_E_DINO_FERRARI.svg'),
    CIRCUIT_DE_MONACO: getImageBaseUrl('CIRCUIT_DE_MONACO.svg'),
    CIRCUIT_DE_BARCELONA_CATALUNYA: getImageBaseUrl('CIRCUIT_DE_BARCELONA_CATALUNYA.svg'),
    CIRCUIT_GILLES_VILLENEUVE: getImageBaseUrl('CIRCUIT_GILLES_VILLENEUVE.svg'),
    RED_BULL_RING: getImageBaseUrl('RED_BULL_RING.svg'),
    SILVERSTONE_CIRCUIT: getImageBaseUrl('SILVERSTONE_CIRCUIT.svg'),
    HUNGARORING: getImageBaseUrl('HUNGARORING.svg'),
    SPA_FRANCORCHAMPS: getImageBaseUrl('SPA_FRANCORCHAMPS.svg'),
    CIRCUIT_ZANDVOORT: getImageBaseUrl('CIRCUIT_ZANDVOORT.svg'),
    MARINA_BAY_CIRCUIT: getImageBaseUrl('MARINA_BAY_CIRCUIT.svg'),
    SUZUKA_CIRCUIT: getImageBaseUrl('SUZUKA_CIRCUIT.svg'),
    LOSAIL_INTERNATIONAL_CIRCUIT: getImageBaseUrl('LOSAIL_INTERNATIONAL_CIRCUIT.svg'),
    CIRCUIT_OF_THE_AMERICAS: getImageBaseUrl('CIRCUIT_OF_THE_AMERICAS.svg'),
    AUTODROMO_HERMANOS_RODRIGUEZ: getImageBaseUrl('AUTODROMO_HERMANOS_RODRIGUEZ.svg'),
    AUTODROMO_JOSE_CARLOS_PACE: getImageBaseUrl('AUTODROMO_JOSE_CARLOS_PACE.svg'),
    LAS_VEGAS: getImageBaseUrl('LAS_VEGAS.svg'),
    YAS_MARINA_CIRCUIT: getImageBaseUrl('YAS_MARINA_CIRCUIT.svg'),
    
    H2H:getImageBaseUrl('h2h.svg'),
    PL_NEW:getImageBaseUrl('pl-new.png'), 
    NO_DATA_VIEW:getImageBaseUrl('no-data-view.png'), 


    DFS1:getImageBaseUrl('DFS1.png'),
    DFS2:getImageBaseUrl('DFS2.png'),
    DFS3:getImageBaseUrl('DFS3.png'),
    DFS4:getImageBaseUrl('DFS4.png'),
    DFS5:getImageBaseUrl('DFS5.png'),
    DFS6:getImageBaseUrl('DFS6.png'),
    
    BUILD_A_CHAMPION:getImageBaseUrl('build-a-champion.png'), 
    CHALLENGE_ONE:getImageBaseUrl('challenge-one.png'), 
    PLAY_OUR_MATCH:getImageBaseUrl('play-your-match.png'),     
    IMAGE_IMAGE:getImageBaseUrl('img_3x.png'),
    QR_IMG_BKP :getImageBaseUrl('FantasyQRCode1.png'),
    NDF_IMAGE :getImageBaseUrl('ndfx3.png'),

    DFSINT1:getImageBaseUrl('DFSINT1.png'),
    DFSINT2:getImageBaseUrl('DFSINT2.png'),
    DFSINT3:getImageBaseUrl('DFSINT3.png'),
    DFSINT4:getImageBaseUrl('DFSINT4.png'),
    DFSINT5:getImageBaseUrl('DFSINT5.png'),

    DFS_INT11:getImageBaseUrl('DFS_INT11.png'),
    PREDICTION_IMG:getImageBaseUrl('prediction-img.png'),

    TOUR_LEADERBOARD:getImageBaseUrl('tour_leader.png'),
    LEAD_TROPHY:getImageBaseUrl('lead-trophy.png'),
    TROPHY_DFS:getImageBaseUrl('trophy2.png'),

    ALL_TEAM_ALL_FIX: getImageBaseUrl('all-team-all-fix.png'),
    OTHER_TEAM: getImageBaseUrl('other-team.png'),
    TOP_GAMES: getImageBaseUrl('top-games.png'),
    ALL_GAMES: getImageBaseUrl('all-games.png'),


    Sports_Hub_Quiz_Img:getImageBaseUrl('sportsHubQuiz.png'),
    Sport_Redeem_Img:getImageBaseUrl('Sports-Redeem.png'),
   
    
    SECOND_INNINIG_IMG:getImageBaseUrl('second-inning-img.png'),
    FILE_IMG_SECOND : getImageBaseUrl('file-img-second.png'),
    TROPHY_IMG_SECOND : getImageBaseUrl('tropy-img-second.png'),
    FILE_IMG : getImageBaseUrl('file-img.png'),
    PREDICTION_IMG:getImageBaseUrl('prediction-img.png'),

    HTP1:getImageBaseUrl('HTP1.png'),
    HTP2:getImageBaseUrl('HTP2.png'),
    HTP3:getImageBaseUrl('HTP3.png'),
    PATH:getImageBaseUrl('path.png'),
    PATH1:getImageBaseUrl('path1.png'),
    ALL_HTP:getImageBaseUrl('all-htp.png'),
    DFS_TMENT_IMG:getImageBaseUrl('dfs-tment-img.png'),
    DFS_TMENT_RULES_IMG:getImageBaseUrl('dfs-tmnt-rules-img.png'),
    TOP_GAMES_THREE : getImageBaseUrl('top-games-three.png'),

    "tourgame_mix_tennis.png": getImageBaseUrl('tourgame_tennis.png'), 
    "tourgame_tennis_women.png": getImageBaseUrl('tourgame_women.png'), 
    "tourgame_tennis_man.png": getImageBaseUrl('tourgame_man.png'), 


    //featured-league
    CRICKET_1 : getImageBaseUrl('cricket1.png'),
    BASEBALL_1 : getImageBaseUrl('baseball1.png'),
    BASKETBALL_1 : getImageBaseUrl('basketball1.png'),
    FL1 : getImageBaseUrl('fila.png'),
    NFL_1 : getImageBaseUrl('nfl1.png'),
    SOCCER_1 : getImageBaseUrl('soccer1.png'),
    TENNIS_1 : getImageBaseUrl('tennis1.png'),

    BADMINTON_1 : getImageBaseUrl('Badminton1.png'),
    NCAA_1 : getImageBaseUrl('NCAA1.png'),
    RUGBY_1 : getImageBaseUrl('rugby1.png'),
    HOCKEY_1 : getImageBaseUrl('hockey1.png'),
    GOLF_1 : getImageBaseUrl('golf1.png'),
    KABADDI_1 : getImageBaseUrl('kabaddi1.png'),

    TROPHY_WON_DFS : getImageBaseUrl('trophy-won.png'),
    MAKE_TEAM:getImageBaseUrl('make-team.png'),
    PICK_DEAL:getImageBaseUrl('pick-deal-img.png'),
    CASHBACK_IMG:getImageBaseUrl('cashback-img.png'), 
    

    // =================== Desktop Images ================
    ICON_APPLE_APP:getImageBaseUrl('icon-apple-app.png'),
    ICON_ANDROID_APP:getImageBaseUrl('icon-android-app.png'),


    HOW_TO_SLIDE_1: getImageBaseUrl('1h2p.png'),
    HOW_TO_SLIDE_2: getImageBaseUrl('2h2p.png'),
    HOW_TO_SLIDE_3: getImageBaseUrl('3h2p.png'),
    HOW_TO_SLIDE_4: getImageBaseUrl('4h2p.png'),
    AD_BANNER:getImageBaseUrl('ad-banner.png'),
     WIDGET_IMG: getImageBaseUrl('widget-img.png'),
    opinion_trade_fantasy:getImageBaseUrl('opinion_trade_fantasy.png'),

}
export default Images;