const Images = {
    HEADER_LOGO: require('../assets/img/logo@3x.png'),
    DEFAULT_AVTAR: require('../assets/img/default-avtar.png'),
    ASIDE_LOGO_WHITE: require('../assets/img/aside-logo-white.png'),
    NEXT: require('../assets/img/next.png'),
    PREV: require('../assets/img/prev.png'),
    apple_pay: require('../assets/img/apple-pay.png'),
    paymet_success: require('../assets/img/paymet-success.png'),
    forgot_link_success: require('../assets/img/forgot-link-success.png'),
    showcase_video: require('../assets/img/showcase.png'),
    showcase_work: require('../assets/img/work.png'),
    showcase_reel: require('../assets/img/reel.png'),
    PLACEHOLDER_IMAGE: 'https://via.placeholder.com/1265x1544.png',
    DEFAULT_BANNER: require('../assets/img/default-profile-banner.jpg'),
    HYD: require('../assets/img/Hyderabad.png'),
    KOL: require('../assets/img/Kolkata.png'),
    BELL: require('../assets/img/bell.png'),
    MSG: require('../assets/img/msg.png'),
    LIST: require('../assets/img/list.png'),
    SMONEY: require('../assets/img/SAMPLE MONEY.png'),
    FOOTBALWP: require('../assets/img/Footballwatchparty.png'),
    COFFEESM: require('../assets/img/COFFEE_SHOP_MEETING.png'),
    TWITTER: require('../assets/img/twitter.png'),
     INSTA: require('../assets/img/insta.png'),
     EYE: require('../assets/img/preview.png'),
     SHAPE: require('../assets/img/Shape.png'),
     DROPDOWN: require('../assets/img/dropdown.png'),
     DROPDOWNDARK: require('../assets/img/dropdarkdown.png'),
     PIN: require('../assets/img/pin.png'),
     Bicon: require('../assets/img/Bicon.png'),
     Micon: require('../assets/img/Micon.png'),
     Picon: require('../assets/img/Picon.png'),
     Sicon: require('../assets/img/Staricon.png'),
     Pinpink: require('../assets/img/pinpink.png'),
     INFO: require('../assets/img/info.png'),

}
export default Images;