
 var constant = {
 	"TABLE_PREFIX":"vi_",
 	"LINEUP":"lineup_",
 	"NORMAL_LINEUP":"lineup",
 	"LINEUP_MASTER":"lineup_master",
 	"LINEUP_MASTER_CONTEST":"lineup_master_contest",
 	"CONTEST":"contest",
 	"LEAGUE":"league",
 	"MASTER_SPORTS":"master_sports",
 	"LEAGUE":"league",
 	"COLLECTION_SEASON":"collection_season",
 	"SEASON":"season",
 	"PLAYER":"player",
 	"GAME_PLAYER_SCORING":"game_player_scoring",
 	"COLLECTION_SEASON":"collection_season",
 	"TEAM_LEAGUE":"team_league",
 	"TEAM":"team",
 	"PLAYER_TEAM":"player_team",
 	"MASTER_LINEUP_POSITION":"master_lineup_position",
 	"COLLECTION_MASTER":"collection_master",
	"PREDICTION_MASTER":"vi_prediction_master",
	"PREDICTION_OPTION":"vi_prediction_option",
	"USER_PREDICTION":"vi_user_prediction",
	"TWEET":"vi_tweet",
	"HASHTAGS":"vi_hashtags",
	"REDIS_EXPIRE":3600,
	"DEFAULT_DATETIME":"",
	"DEFAULT_DATETIME_FORMAT":"YYYY-MM-DD HH:mm:ss",
	"DEFAULT_TWEET_DATETIME_FORMAT":"D MMM YYYY hh:mm A",
	"ENABLE_REDIS":false,
	"CACHE_PREFIX":"pbl_",
	"TWITTER_HASHTAG_HANDLE":"twitter_hashtag_handle_",
	"SITE_TITLE":"Funtasy11",
	"MONGO_COLL_LINEUPS":"lineups",
	"MONGO_COLL_COMPLETED_LINEUPS":"completed_lineups",
	"MONGO_COLL_ARCHIVE_COMPLETED_LINEUPS":"archive_completed_lineups",
	"FIXTURE_CONTEST_COLLECTION":"fixture_contest_collection",
	"USER_COMPLETED_CONTEST":"user_completed_contest",
	"SEASON_MATCHES_COLLECTION":"season_matches",
	"CATEGORY":"vi_category",
	"TOURNAMENT_SEASON":"tournament_season",
 	"TOURNAMENT_TEAM":"tournament_team",
 	"TOURNAMENT_LINEUP":"tournament_lineup",
 	"TOURNAMENT":"tournament",
	"USER":"vi_user",
	"COLLECTION":"collection",
	"COLLECTION_STOCK":"collection_stock",
	"STOCK_HISTORY":"stock_history",
	"STOCK":"stock",
	"STOCK_TYPE":"stock_type",
	"STOCK_LINEUP":"lineup",
 	"APP_CONFIG":"app_config",
 	"COLLECTION":"collection",
 	"USER_CONTEST":"user_contest",
 	"USER_TEAM":"user_team"
}

module.exports = constant;