<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Cricket_scoring_rules_update extends CI_Migration {

	public function up() 
	{
		//Trasaction start
    	$this->db->trans_strict(TRUE);
    	$this->db->trans_start();
   	
    	//Add two filed in cricket statistics table
    	$sql = "ALTER TABLE ".$this->db->dbprefix(GAME_STATISTICS_CRICKET)." ADD `bowling_bowled` INT NOT NULL DEFAULT '0' AFTER `bowling_wickets`, ADD `bowling_lbw` INT NULL DEFAULT '0' AFTER `bowling_bowled`;";
    	$this->db->query($sql);

    	//update unique key
    	$sql = "ALTER TABLE ".$this->db->dbprefix(MASTER_SCORING_RULES)." ADD UNIQUE( `master_scoring_category_id`, `format`, `meta_key`);";
    	$this->db->query($sql);

    	//Add new rules for TEST
    	$sql = "DELETE FROM ".$this->db->dbprefix(MASTER_SCORING_RULES)." WHERE `format` = 2 AND master_scoring_category_id IN (14,15);";
    	$this->db->query($sql);

    	$sql = "INSERT INTO ".$this->db->dbprefix(MASTER_SCORING_RULES)." (`master_scoring_category_id`, `format`, `score_position`, `en_score_position`, `hi_score_position`, `guj_score_position`, `fr_score_position`, `ben_score_position`, `pun_score_position`, `tam_score_position`, `th_score_position`, `score_points`, `points_unit`, `meta_key`, `meta_key_alias`, `ru_score_position`, `id_score_position`, `tl_score_position`, `zh_score_position`, `kn_score_position`) VALUES
			(14, 2, 'In Starting 11', 'In Starting 11', '11 की शुरुआत में', '11 શરૂ કરી રહ્યા છીએ', 'Au départ 11', '11 শুরুতে', '11 ਦੀ ਸ਼ੁਰੂਆਤ ਵਿੱਚ', 'தொடக்க 11 இல்', 'ในการเริ่มต้น 11', 4, 0, 'STARTING_11', '', 'В старте 11', 'Di Mulai 11', 'Sa Simula 11', '在首发 11', 'ಪ್ರಾರಂಭ 11 ರಲ್ಲಿ'),
		(14, 2, 'Run', 'Run', 'रन', 'ચલાવો', 'Cours', 'চালান', 'ਰਨ', 'ஓடு', 'วิ่ง', 1, 0, 'RUN', '', 'ЗАПУСТИТЬ', 'LARI', 'TUMATAKBO', '跑步', 'ಓಡು'),
		(14, 2, 'Wicket (Excluding Run Out)', 'Wicket (Excluding Run Out)', 'विकेट (रन आउट को छोड़कर)', 'વિકેટ (રન આઉટ સિવાય)', 'Wicket (à l\'exclusion de l\'épuisement)', 'উইকেট (রান আউট বাদে)', 'ਵਿਕਟ (ਰਨ ਆ Outਟ ਨੂੰ ਛੱਡ ਕੇ)', 'விக்கெட் (ரன் அவுட் தவிர)', 'ประตู (ไม่รวมหมด)', 16, 0, 'WICKET', '', 'Калитка (исключая выбег)', 'Gawang (Tidak Termasuk Kehabisan)', 'Wicket (Hindi kasama ang Naubos na)', '检票口（不包括用完）', 'ವಿಕೆಟ್ (ರನ್ Out ಟ್ ಹೊರತುಪಡಿಸಿ)'),
		(14, 2, 'Catch', 'Catch', 'कैच', 'કૅચસ', 'Attraper', 'ধরা', 'ਫੜੋ', 'பிடி', 'จับ', 8, 0, 'CATCH', '', 'Ловить', 'Menangkap', 'Mahuli', '抓住', 'ಕ್ಯಾಚ್'),
		(14, 2, 'Stumping', 'Stumping', 'स्टम्पिंग', 'સ્ટમપિંગ', 'Assommer', 'স্টাম্পিং', 'স্টাম্পিং', 'ஸ்டம்பிங்', 'ตอ', 12, 0, 'STUMPING', '', 'Stumping', 'Membingungkan', 'Nakaka-stump', '绊倒', 'ಸ್ಟಂಪಿಂಗ್'),
		(14, 2, 'Run out (Thrower)', 'Run out (Thrower)', 'रन​-आउट (फेंकने वाला)', 'રન આઉટ (સીધી હિટ)', 'Run out (lanceur)', 'রান আউট (নিক্ষিপ্ত)', 'ਰਨ ਆ outਟ (ਥ੍ਰੋਅਰ)', 'ரன் அவுட் (வீசுபவர்)', 'หมด (Thrower)', 6, 0, 'RUN_OUT_THROWER', '', 'Беги (Метатель)', 'Habis (Pelempar)', 'Naubusan (Magtapon)', '跑出（投掷者）', 'ರನ್ out ಟ್ (ಥ್ರೋವರ್)'),
		(14, 2, 'Run out (Catcher)', 'Run out (Catcher)', 'रन​-आउट (पकड़ने वाला)', 'રન આઉટ (કેચર)', 'Run out (receveur)', 'রান আউট (ক্যাচার)', 'ਰਨ ਆ outਟ (ਕੈਚਰ)', 'ரன் அவுட் (பற்றும்)', 'หมด (Catcher)', 6, 0, 'RUN_OUT_CATCHER', '', 'Беги (Catcher)', 'Habis (Penangkap)', 'Naubusan (Catcher)', '跑出（捕手）', 'ರನ್ out ಟ್ (ಕ್ಯಾಚರ್)'),
		(14, 2, 'Run out (Direct hit)', 'Run out (Direct hit)', 'रन आउट (डायरेक्ट हिट)', 'રન આઉટ (સીધી હિટ)', 'Run out (coup direct)', 'রান আউট (সরাসরি আঘাত)', 'ਰਨ ਆ outਟ (ਸਿੱਧੀ ਹਿੱਟ)', 'ரன் அவுட் (நேரடி வெற்றி)', 'หมด (ตีโดยตรง)', 12, 0, 'RUN_OUT_DIRECT_HIT', '', 'Бежать (прямое попадание)', 'Habis (Tembak langsung)', 'Naubusan (Direktang hit)', '跑出（直接命中）', 'ರನ್ out ಟ್ (ಡೈರೆಕ್ಟ್ ಹಿಟ್)'),
		(14, 2, 'Dismissal for a duck (Batsman, Wicket-Keeper & All-Rounder)', 'Dismissal for a duck (Batsman, Wicket-Keeper & All-Rounder)', 'शून्य  पर आउट (बल्लेबाज, विकेटकीपर और ऑलराउंडर)', 'શૂન્ય માટે બરતરફ (બેટ્સમેન, વિકેટ-કીપર અને ઓલ-રાઉન્ડર)', 'Licenciement pour un zéro (Batsman, Wicket-Keeper & All-Rounder)', 'শূন্যের জন্য বরখাস্ত (ব্যাটসম্যান, উইকেট-কিপার এবং অল-রাউন্ডার)', 'ਸਿਫ਼ਰ (ਬੈਟਸਮੈਨ, ਵਿਕਟ ਕੀਪਰ ਅਤੇ ਆਲ-ਰਾ Rਂਡਰ) ਲਈ ਬਰਖਾਸਤਗੀ', 'பூஜ்ஜியத்திற்கான தள்ளுபடி (பேட்ஸ்மேன், விக்கெட் கீப்பர் & ஆல்-ரவுண்டர்)', 'การไล่ออกเป็นศูนย์ (Batsman, Wicket-Keeper & All-Rounder)', -4, 0, 'DUCK', '', 'Увольнение за утку (Бэтсмен, Хранитель калитки и Универсал)', 'Pemberhentian untuk bebek (Batsman, Penjaga Gawang & All-Rounder)', 'Pag-alis para sa isang pato (Batsman, Wicket-Keeper & All-Rounder)', '解雇鸭子（击球手，守门员和全能者）', 'ಶೂನ್ಯಕ್ಕೆ ವಜಾಗೊಳಿಸುವುದು (ಬ್ಯಾಟ್ಸ್‌ಮನ್, ವಿಕೆಟ್ ಕೀಪರ್ ಮತ್ತು ಆಲ್-ರೌಂಡರ್)'),
		(15, 2, 'Boundary Bonus', 'Boundary Bonus', 'सीमा बोनस', 'બાઉન્ડ્રી બોનસ', 'Bonus de limite', 'বাউন্ডারি বোনাস', 'ਸੀਮਾ ਬੋਨਸ', 'எல்லை போனஸ்', 'โบนัสขอบเขต', 1, 0, 'FOUR', '', 'Граничный бонус', 'Bonus Batas', 'Boundary Bonus', '边界奖金', 'ಗಡಿ ಬೋನಸ್'),
		(15, 2, 'Six Bonus', 'Six Bonus', 'छह बोनस', 'છ બોનસ', 'Six bonus', 'ছয় বোনাস', 'ਛੇ ਬੋਨਸ', 'ஆறு போனஸ்', 'หกโบนัส', 2, 0, 'SIX', '', 'Шесть бонусов', 'Enam Bonus', 'Anim na Bonus', '六分红', 'ಆರು ಬೋನಸ್'),
		(15, 2, 'Half-century Bonus', 'Half-century Bonus', 'अर्धशतक बोनस', 'અડધી સદીનો બોનસ', 'Bonus dun demi-siècle', 'অর্ধ শতাব্দীর বোনাস', 'ਅੱਧੀ ਸਦੀ ਦਾ ਬੋਨਸ', 'அரை நூற்றாண்டு போனஸ்', 'โบนัสครึ่งศตวรรษ', 4, 0, 'HALF_CENTURY', '', 'Бонус за полвека', 'Bonus setengah abad', 'Half-siglo Bonus', '半个世纪奖金', 'ಅರ್ಧ ಶತಮಾನದ ಬೋನಸ್'),
		(15, 2, 'Century Bonus', 'Century Bonus', 'शतक बोनस', 'સદી બોનસ', 'Bonus du siècle', 'সেঞ্চুরি বোনাস', 'ਸਦੀ ਬੋਨਸ', 'நூற்றாண்டு போனஸ்', 'โบนัสศตวรรษ', 8, 0, 'CENTURY', '', 'Бонус века', 'Bonus Abad', 'Bonus sa Siglo', '世纪红利', 'ಸೆಂಚುರಿ ಬೋನಸ್'),
		(15, 2, '4 Wicket Bonus', '4 Wicket Bonus', '4 विकेट बोनस', '4 વિકેટ બોનસ', 'Bonus de 4 guichets', '4 উইকেট বোনাস', '4 ਵਿਕਟ ਬੋਨਸ', '4 விக்கெட் போனஸ்', 'โบนัส 4 ประตู', 4, 0, 'FOUR_WICKET', '', '4 Бонус калитки', 'Bonus 4 Gawang', '4 Bonus sa Wicket', '4 检票奖金', '4 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 2, '5 Wicket Bonus', '5 Wicket Bonus', '5 विकेट बोनस', '5 વિકેટ બોનસ', 'Bonus de 5 guichets', '5 উইকেট বোনাস', '5 ਵਿਕਟ ਬੋਨਸ', '5 விக்கெட் போனஸ்', 'โบนัส 5 ประตู', 8, 0, 'FIVE_WICKET', '', '5 Бонус калитки', 'Bonus 5 Gawang', '5 Bonus sa Wicket', '5 检票奖金', '5 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 2, 'Bonus (LBW / Bowled)', 'Bonus (LBW / Bowled)', 'बोनस (एलबीडब्ल्यू / बोल्ड)', 'બોનસ (એલબીડબલ્યુ / બાઉલ્ડ)', 'Bonus (LBW / Bowled)', 'বোনাস (এলবিডাব্লু / বোল্ড)', 'ਬੋਨਸ (ਐਲਬੀਡਬਲਯੂ / ਬੋਲਡ)', 'போனஸ் (எல்.பி.டபிள்யூ / பவுல்ட்)', 'โบนัส (ปอนด์ / โบว์ลิ่ง)', 8, 0, 'LBW_BOWLED', '', 'Бонус (LBW / Bowled)', 'Bonus (BBLR / Mabuk)', 'Bonus (LBW / Bowled)', '奖金（LBW / 保龄球）', 'ಬೋನಸ್ (ಎಲ್ಬಿಡಬ್ಲ್ಯೂ / ಬೌಲ್ಡ್)');";
		$this->db->query($sql);

		//Add Rules for ODI
		$sql = "DELETE FROM ".$this->db->dbprefix(MASTER_SCORING_RULES)." WHERE `format` = 1 AND master_scoring_category_id IN (14,15,16,17);";
    	$this->db->query($sql);

    	$sql = "INSERT INTO ".$this->db->dbprefix(MASTER_SCORING_RULES)." (`master_scoring_category_id`, `format`, `score_position`, `en_score_position`, `hi_score_position`, `guj_score_position`, `fr_score_position`, `ben_score_position`, `pun_score_position`, `tam_score_position`, `th_score_position`, `score_points`, `points_unit`, `meta_key`, `meta_key_alias`, `ru_score_position`, `id_score_position`, `tl_score_position`, `zh_score_position`, `kn_score_position`) VALUES
    	(14, 1, 'In Starting 11', 'In Starting 11', '11 की शुरुआत में', '11 શરૂ કરી રહ્યા છીએ', 'Au départ 11', '11 শুরুতে', '11 ਦੀ ਸ਼ੁਰੂਆਤ ਵਿੱਚ', 'தொடக்க 11 இல்', 'ในการเริ่มต้น 11', 4, 0, 'STARTING_11', '', 'В старте 11', 'Di Mulai 11', 'Sa Simula 11', '在首发 11', 'ಪ್ರಾರಂಭ 11 ರಲ್ಲಿ'),
		(14, 1, 'Run', 'Run', 'रन', 'ચલાવો', 'Cours', 'চালান', 'ਰਨ', 'ஓடு', 'วิ่ง', 1, 0, 'RUN', '', 'ЗАПУСТИТЬ', 'LARI', 'TUMATAKBO', '跑步', 'ಓಡು'),
		(14, 1, 'Wicket (Excluding Run Out)', 'Wicket Excluding Run Out', 'विकेट (रन आउट को छोड़कर)', 'વિકેટ (રન આઉટ સિવાય)', 'Wicket (à l\'exclusion de l\'épuisement)', 'উইকেট (রান আউট বাদে)', 'ਵਿਕਟ (ਰਨ ਆ Outਟ ਨੂੰ ਛੱਡ ਕੇ)', 'விக்கெட் (ரன் அவுட் தவிர)', 'ประตู (ไม่รวมหมด)', 25, 0, 'WICKET', '', 'Калитка (исключая выбег)', 'Gawang (Tidak Termasuk Kehabisan)', 'Wicket (Hindi kasama ang Naubos na)', '检票口（不包括用完）', 'ವಿಕೆಟ್ (ರನ್ Out ಟ್ ಹೊರತುಪಡಿಸಿ)'),
		(14, 1, 'Catch', 'Catch', 'कैच', 'કૅચસ', 'Attraper', 'ধরা', 'ਫੜੋ', 'பிடி', 'จับ', 8, 0, 'CATCH', '', 'Ловить', 'Menangkap', 'Mahuli', '抓住', 'ಕ್ಯಾಚ್'),
		(14, 1, 'Stumping', 'Stumping', 'स्टम्पिंग', 'સ્ટમપિંગ', 'Assommer', 'স্টাম্পিং', 'স্টাম্পিং', 'ஸ்டம்பிங்', 'ตอ', 12, 0, 'STUMPING', '', 'Stumping', 'Membingungkan', 'Nakaka-stump', '绊倒', 'ಸ್ಟಂಪಿಂಗ್'),
		(14, 1, 'Run out (Thrower)', 'Run out (Thrower)', 'रन​-आउट (फेंकने वाला)', 'રન આઉટ (ફેંકનાર)', 'Run out (lanceur)', 'রান আউট (নিক্ষিপ্ত)', 'ਰਨ ਆ outਟ (ਥ੍ਰੋਅਰ)', 'ரன் அவுட் (வீசுபவர்)', 'หมด (Thrower)', 6, 0, 'RUN_OUT_THROWER', '', 'Беги (Метатель)', 'Habis (Pelempar)', 'Naubusan (Magtapon)', '跑出（投掷者）', 'ರನ್ out ಟ್ (ಥ್ರೋವರ್)'),
		(14, 1, 'Run out (Catcher)', 'Run out (Catcher)', 'रन​-आउट (पकड़ने वाला)', 'રન આઉટ (કેચર)', 'Run out (receveur)', 'রান আউট (ক্যাচার)', 'ਰਨ ਆ outਟ (ਕੈਚਰ)', 'ரன் அவுட் (பற்றும்)', 'หมด (Catcher)', 6, 0, 'RUN_OUT_CATCHER', '', 'Беги (Catcher)', 'Habis (Penangkap)', 'Naubusan (Catcher)', '跑出（捕手）', 'ರನ್ out ಟ್ (ಕ್ಯಾಚರ್)'),
		(14, 1, 'Run out (Direct hit)', 'Run out (Direct hit)', 'रन आउट (डायरेक्ट हिट)', 'રન આઉટ (સીધી હિટ)', 'Run out (coup direct)', 'রান আউট (সরাসরি আঘাত)', 'ਰਨ ਆ outਟ (ਸਿੱਧੀ ਹਿੱਟ)', 'ரன் அவுட் (நேரடி வெற்றி)', 'หมด (ตีโดยตรง)', 12, 0, 'RUN_OUT_DIRECT_HIT', '', 'Бежать (прямое попадание)', 'Habis (Tembak langsung)', 'Naubusan (Direktang hit)', '跑出（直接命中）', 'ರನ್ out ಟ್ (ಡೈರೆಕ್ಟ್ ಹಿಟ್)'),
		(14, 1, 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'शून्य  पर आउट (बल्लेबाज, विकेटकीपर और ऑलराउंडर)', 'શૂન્ય માટે બરતરફ (બેટ્સમેન, વિકેટ-કીપર અને ઓલ-રાઉન્ડર)', 'Licenciement pour un zéro (Batsman, Wicket-Keeper & All-Rounder)', 'শূন্যের জন্য বরখাস্ত (ব্যাটসম্যান, উইকেট-কিপার এবং অল-রাউন্ডার)', 'ਸਿਫ਼ਰ (ਬੈਟਸਮੈਨ, ਵਿਕਟ ਕੀਪਰ ਅਤੇ ਆਲ-ਰਾ Rਂਡਰ) ਲਈ ਬਰਖਾਸਤਗੀ', 'பூஜ்ஜியத்திற்கான தள்ளுபடி (பேட்ஸ்மேன், விக்கெட் கீப்பர் & ஆல்-ரவுண்டர்)', 'การไล่ออกเป็นศูนย์ (Batsman, Wicket-Keeper & All-Rounder)', -3, 0, 'DUCK', '', 'Увольнение за утку (Бэтсмен, Хранитель калитки и Универсал)', 'Pemberhentian untuk bebek (Batsman, Penjaga Gawang & All-Rounder)', 'Pag-alis para sa isang pato (Batsman, Wicket-Keeper & All-Rounder)', '解雇鸭子（击球手，守门员和全能者）', 'ಶೂನ್ಯಕ್ಕೆ ವಜಾಗೊಳಿಸುವುದು (ಬ್ಯಾಟ್ಸ್‌ಮನ್, ವಿಕೆಟ್ ಕೀಪರ್ ಮತ್ತು ಆಲ್-ರೌಂಡರ್)'),
		(15, 1, 'Boundary Bonus', 'Boundary Bonus', 'सीमा बोनस', 'બાઉન્ડ્રી બોનસ', 'Bonus de limite', 'বাউন্ডারি বোনাস', 'ਸੀਮਾ ਬੋਨਸ', 'எல்லை போனஸ்', 'โบนัสขอบเขต', 1, 0, 'FOUR', '', 'Граничный бонус', 'Bonus Batas', 'Boundary Bonus', '边界奖金', 'ಗಡಿ ಬೋನಸ್'),
		(15, 1, 'Six Bonus', 'Six Bonus', 'छह बोनस', 'છ બોનસ', 'Six bonus', 'ছয় বোনাস', 'ਛੇ ਬੋਨਸ', 'ஆறு போனஸ்', 'หกโบนัส', 2, 0, 'SIX', '', 'Шесть бонусов', 'Enam Bonus', 'Anim na Bonus', '六分红', 'ಆರು ಬೋನಸ್'),
		(15, 1, 'Half-century Bonus ', 'Half-century Bonus ', 'अर्धशतक बोनस', 'અડધી સદીનો બોનસ', 'Bonus dun demi-siècle', 'অর্ধ শতাব্দীর বোনাস', 'ਅੱਧੀ ਸਦੀ ਦਾ ਬੋਨਸ', 'அரை நூற்றாண்டு போனஸ்', 'โบนัสครึ่งศตวรรษ', 4, 0, 'HALF_CENTURY', '', 'Бонус за полвека', 'Bonus setengah abad', 'Half-siglo Bonus', '半个世纪奖金', 'ಅರ್ಧ ಶತಮಾನದ ಬೋನಸ್'),
		(15, 1, 'Century Bonus', 'Century Bonus', 'शतक बोनस', 'સદી બોનસ', 'Bonus du siècle', 'সেঞ্চুরি বোনাস', 'ਸਦੀ ਬੋਨਸ', 'நூற்றாண்டு போனஸ்', 'โบนัสศตวรรษ', 8, 0, 'CENTURY', '', 'Бонус века', 'Bonus Abad', 'Bonus sa Siglo', '世纪红利', 'ಸೆಂಚುರಿ ಬೋನಸ್'),
		(15, 1, 'Maiden over', 'Maiden over', 'मेडेन ओवर', 'મેઇડન ઓવર', 'Maiden sur', 'মেয়ের উপর', 'ਕੁਆਰੀ ਹੋ ਗਈ', 'மெய்டன் ஓவர்', 'หญิงสาวมากกว่า', 4, 0, 'MAIDEN_OVER', '', 'Дева закончилась', 'Gadis atas', 'Pagdalaga ng dalaga', '处女过', 'ಮೇಡನ್ ಓವರ್'),
		(15, 1, '3 Catch Bonus', '3 Catch Bonus', '3 कैच बोनस', '3 બોનસ બો', '3 Bonus de capture', '3 ক্যাচ বোনাস', '3 ਕੈਚ ਬੋਨਸ', '3 கேட்ச் போனஸ்', '3 จับโบนัส', 4, 0, 'CATCH_3', '', '3 Бонус улова', '3 Bonus Tangkapan', '3 Makibalita Bonus', '3 捕获奖金', '3 ಕ್ಯಾಚ್ ಬೋನಸ್'),
		(15, 1, '4 Wicket Bonus', '4 Wicket Bonus', '4 विकेट बोनस', '4 વિકેટ બોનસ', 'Bonus de 4 guichets', '4 উইকেট বোনাস', '4 ਵਿਕਟ ਬੋਨਸ', '4 விக்கெட் போனஸ்', 'โบนัส 4 ประตู', 4, 0, 'FOUR_WICKET', '', '4 Бонус калитки', 'Bonus 4 Gawang', '4 Bonus sa Wicket', '4 检票奖金', '4 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 1, '5 Wicket Bonus', '5 Wicket Bonus', '5 विकेट बोनस', '5 વિકેટ બોનસ', 'Bonus de 5 guichets', '5 উইকেট বোনাস', '5 ਵਿਕਟ ਬੋਨਸ', '5 விக்கெட் போனஸ்', 'โบนัส 5 ประตู', 8, 0, 'FIVE_WICKET', '', '5 Бонус калитки', 'Bonus 5 Gawang', '5 Bonus sa Wicket', '5 检票奖金', '5 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 1, 'Bonus (LBW / Bowled)', 'Bonus (LBW / Bowled)', 'बोनस (एलबीडब्ल्यू / बोल्ड)', 'બોનસ (એલબીડબલ્યુ / બાઉલ્ડ)', 'Bonus (LBW / Bowled)', 'বোনাস (এলবিডাব্লু / বোল্ড)', 'ਬੋਨਸ (ਐਲਬੀਡਬਲਯੂ / ਬੋਲਡ)', 'போனஸ் (எல்.பி.டபிள்யூ / பவுல்ட்)', 'โบนัส (ปอนด์ / โบว์ลิ่ง)', 8, 0, 'LBW_BOWLED', '', 'Бонус (LBW / Bowled)', 'Bonus (BBLR / Mabuk)', 'Bonus (LBW / Bowled)', '奖金（LBW / 保龄球）', 'ಬೋನಸ್ (ಎಲ್ಬಿಡಬ್ಲ್ಯೂ / ಬೌಲ್ಡ್)'),
		(16, 1, 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'ओवर की संख्या जिस्के ऊपर​ स्कोरिंग नियम लागू होंगे', 'ઇકોનોમી રેટ માટે નીચેના નિયમોની ગણતરી માટે બોલ્ડ કરવા માટે ન્યૂનતમ ઓવર', 'Nombre minimum de overs à jouer pour calculer les règles ci-dessous pour le tarif économique', 'অর্থনীতি হারের নিয়ম নীচে গণনা করার জন্য বোল করা ন্যূনতম সংখ্যা ওভার', 'ਆਰਥਿਕਤਾ ਦਰ ਲਈ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਓਵਰਾਂ ਦੀ ਗਿਣਤੀ', 'பொருளாதார வீதத்திற்கான விதிகளை கீழே கணக்கிடுவதற்கு பந்து வீச வேண்டிய குறைந்தபட்ச ஓவர்கள்', 'จำนวนขั้นต่ำที่จะโค้งคำนับสำหรับการคำนวณด้านล่างกฎสำหรับอัตราประหยัด', 5, 0, 'MINIMUM_BOWLING_BOWLED_OVER', '', 'Минимальное количество оверов для игры в боулинг для расчета следующих правил для экономичного тарифа', 'Jumlah minimum over yang harus di-bow untuk menghitung di bawah aturan untuk Tarif Ekonomi', 'Min bilang ng mga sobra sa bowled para makalkula sa ibaba ang mga patakaran para sa Economy Rate', '用于计算以下经济率规则的最少投球次数', 'ಎಕಾನಮಿ ದರಕ್ಕಾಗಿ ನಿಯಮಗಳನ್ನು ಕೆಳಗೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಬೌಲ್ ಮಾಡಲು ಕನಿಷ್ಠ ಸಂಖ್ಯೆಯ ಓವರ್‌ಗಳು'),
		(16, 1, 'Below 2.5 runs per over', 'Below 2.5 runs per over', '2.5 रन प्रति ओवर से नीचे', '2.5 ઓવર દીઠ રન', 'Moins de 2,5 courses par plus', 'ওভার প্রতি 2.5 রান', '2.5 ਓਵਰਾਂ ਦੇ ਹੇਠਾਂ', 'ஒரு ஓவருக்கு 2.5 ரன்களுக்கு கீழே', 'ต่ำกว่า 2.5 รันต่อโอเวอร์', 6, 0, 'ECONOMY_BELOW_25', '', 'Менее 2,5 пробега за овер', 'Di bawah 2,5 run per over', 'Sa ibaba 2.5 ay tumatakbo bawat higit sa', '每回合低于 2.5 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 2.5 ರನ್‌ಗಳ ಕೆಳಗೆ'),
		(16, 1, 'Between 2.5-3.49 runs per over', 'Between 2.5-3.49 runs per over', '2.5-3.49 रन प्रति ओवर के बीच', '2.5-3.49 વચ્ચે પ્રતિ ઓવર', 'Entre 2,5 et 3,49 courses par over', '2.5-3.49 এর মধ্যে ওভার প্রতি রান', '2.5-3.49 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 2.5 முதல் 3.49 ரன்கள் வரை', 'ระหว่าง 2.5-3.49 รันต่อโอเวอร์', 4, 0, 'ECONOMY_25_349', '', 'От 2,5 до 3,49 пробежек за овер', 'Antara 2.5-3.49 run per over', 'Sa pagitan ng 2.5-3.49 tumatakbo bawat higit', '每次超过 2.5-3.49 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 2.5-3.49 ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 1, 'Between 3.5-4.5 runs per over', 'Between 3.5-4.5 runs per over', '3.5-4.5 रन प्रति ओवर के बीच', '3.5-4.5 વચ્ચે પ્રતિ ઓવર', 'Entre 3,5 et 4,5 courses par over', '3.5-4.5 এর মধ্যে ওভার প্রতি রান', '3.5-4.5 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 3.5 முதல் 4.5 ரன்கள் வரை', 'ระหว่าง 3.5-4.5 รันต่อโอเวอร์', 2, 0, 'ECONOMY_35_45', '', 'От 3,5 до 4,5 пробежек за овер', 'Antara 3,5-4,5 run per over', 'Sa pagitan ng 3.5-4.5 tumatakbo bawat higit', '每回合 3.5-4.5 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 3.5-4.5 ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 1, 'Between 7-8 runs per over', 'Between 7-8 runs per over', '7-8  रन प्रति ओवर के बीच', '7-8  વચ્ચે પ્રતિ ઓવર', 'Entre 7 et 8 courses par over', '7-8  এর মধ্যে ওভার প্রতি রান', '7-8  ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 7 முதல் 8 ரன்கள் வரை', 'ระหว่าง 7-8  รันต่อโอเวอร์', -2, 0, 'ECONOMY_7_8', '', 'От 7-8 пробежек за повтор', 'Antara 7-8 run per over', 'Sa pagitan ng 7-8 tumatakbo bawat higit', '每回合 7-8 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 7-8  ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 1, 'Between 8.01-9 runs per over', 'Between 8.01-9 runs per over', '8.01-9 रन प्रति ओवर के बीच', '8.01-9 વચ્ચે પ્રતિ ઓવર', 'Entre 8,01 et 9 courses par over', '8.01-9 এর মধ্যে ওভার প্রতি রান', '8.01-9 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 8.01 முதல் 9 ரன்கள் வரை', 'ระหว่าง 8.01-9 รันต่อโอเวอร์', -4, 0, 'ECONOMY_801_9', '', 'Между 8.01–9 бегами за овер', 'Antara 8.01-9 run per over', 'Sa pagitan ng 8.01-9 tumatakbo bawat higit', '8.01-9 运行之间', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 8.01-39 ರನ್‌ಗಳ ನಡುವ'),
		(16, 1, 'Above 9 runs per over', 'Above 9 runs per over', '9 रन प्रति ओवर से ऊपर', '9 ઓવર દીઠ રન', 'Au-dessus de 9 courses par over', 'ওভার প্রতি 9 রান উপরে', '9 ਓਵਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 9 ரன்களுக்கு மேல்', 'สูงกว่า 9 รันต่อโอเวอร์', -6, 0, 'ECONOMY_ABOVE_9', '', 'Свыше 9 пробегов за овер', 'Di atas 9 run per over', 'Sa itaas 9 tumatakbo bawat higit sa', '每回合超过 9 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 9 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
		(17, 1, 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'स्ट्राइक रेट के लिए नीचे दिए गए नियमों की गणना के लिए खेली जाने वाली गेंदों की न्यूनतम संख्या (गेंदबाज को छोड़कर)', 'સ્ટ્રાઈક રેટ (બાઉલર સિવાય) ની નીચેના નિયમોની ગણતરી કરવા માટે રમવાના બોલમાંનો મીન નંબર', 'Nombre minimum de balles à jouer pour calculer les règles ci-dessous pour le taux de grève (sauf le quilleur)', 'স্ট্রাইক রেট (বোলার ব্যতীত) নীচের নিয়মের নিচে গণনা করার জন্য ন্যূনতম বল খেলতে হবে', 'ਸਟਰਾਈਕ ਰੇਟ (ਬਾ rulesਲਰ ਨੂੰ ਛੱਡ ਕੇ) ਦੇ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਗੇਂਦਾਂ ਖੇਡੀਆਂ ਜਾਣਗੀਆਂ.', 'ஸ்ட்ரைக் வீதத்திற்கான விதிகளை கீழே கணக்கிட (பந்துவீச்சாளரைத் தவிர) விளையாட வேண்டிய குறைந்தபட்ச பந்துகள்', 'จำนวนลูกขั้นต่ำที่จะเล่นเพื่อคำนวณกฎด้านล่างสำหรับอัตราการตี (ยกเว้นกะลา)', 20, 0, 'MINIMUM_BALL_PLAYED', '', 'Минимальное количество шаров, которые должны быть сыграны для расчета приведенных ниже правил для ставки страйка (кроме боулера)', 'Jumlah minimum bola yang akan dimainkan untuk menghitung di bawah aturan untuk Strike Rate (Kecuali Bowler)', 'Min hindi ng mga bola na dapat i-play para makalkula ang mga patakaran sa ibaba para sa Strike Rate (Maliban sa Bowler)', '计算以下击球率规则的最少球数（保龄球除外）', 'ಸ್ಟ್ರೈಕ್ ರೇಟ್ (ಬೌಲರ್ ಹೊರತುಪಡಿಸಿ) ಗಾಗಿ ಕೆಳಗಿನ ನಿಯಮಗಳನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಆಡಬೇಕಾದ ಕನಿಷ್ಠ ಚೆಂಡುಗಳು'),
		(17, 1, 'Above 140 runs per 100 balls', 'Above 140 runs per 100 balls', 'प्रति 100 गेंदों पर 140 रन से ऊपर', '100 દડામાં 140 રનથી વધુ', 'Au-dessus de 140 pistes pour 100 balles', '100 বল প্রতি 140 রান উপরে', '140 ਦੌੜਾਂ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 140 ரன்களுக்கு மேல்', 'สูงกว่า 140 วิ่งต่อ 100 ลูก', 6, 0, 'STRIKE_RATE_ABOVE_140', '', 'Свыше 140 пробежек на 100 мячей', 'Di atas 140 run per 100 bola', 'Sa itaas 140 tumatakbo bawat 100 bola', '每 100 个球 140 次以上', '100 ಎಸೆತಗಳಿಗೆ 140 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
		(17, 1, 'Between 120.01-140 runs per 100 balls', 'Between 120.01-140 runs per 100 balls', 'प्रति 100 गेंदों पर 120.01-140 रन के बीच', '100 બોલમાં દીઠ 120.01-140 વચ્ચે', 'Entre 120,01-140 pistes pour 100 balles', '120.01-140 এর মধ্যে 100 বল প্রতি রান', '120.01-140 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 120.01-140 ரன்கள் வரை', 'ระหว่าง 120.01-140 วิ่งต่อ 100 ลูก', 4, 0, 'STRIKE_RATE_12001_140', '', '120,01-140 пробежек на 100 мячей', 'Antara 120,01-140 lari per 100 bola', 'Sa pagitan ng 120.01-140 tumatakbo bawat 100 bola', '每 100 个球运行 120.01-140 次', '100 ಎಸೆತಗಳಿಗೆ 120.01-140 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 1, 'Between 100-120 runs per 100 balls', 'Between 100-120 runs per 100 balls', 'प्रति 100 गेंदों पर 100-120 रन के बीच', '100 બોલમાં દીઠ 100-120 વચ્ચે', 'Entre 100-120 pistes pour 100 balles', '100-120 এর মধ্যে 100 বল প্রতি রান', '100-120 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 100-120 ரன்கள் வரை', 'ระหว่าง 100-120 วิ่งต่อ 100 ลูก', 2, 0, 'STRIKE_RATE_100_120', '', 'Между 100-120 пробежками на 100 мячей', 'Antara 100-120 lari per 100 bola', 'Sa pagitan ng 100-120 tumatakbo bawat 100 bola', '每 100 个球运行 100-120 次', '100 ಎಸೆತಗಳಿಗೆ 100-120 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 1, 'Between 40-50 runs per 100 balls', 'Between 40-50 runs per 100 balls', 'प्रति 100 गेंदों पर 40-50 रन के बीच', '100 બોલમાં દીઠ 40-50 વચ્ચે', 'Entre 40-50 pistes pour 100 balles', '40-50 এর মধ্যে 100 বল প্রতি রান', '40-50 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 40-50 ரன்கள் வரை', 'ระหว่าง 40-50 วิ่งต่อ 100 ลูก', -2, 0, 'STRIKE_RATE_40_50', '', 'От 40 до 50 пробежек на 100 мячей', 'Antara 40-50 lari per 100 bola', 'Sa pagitan ng 40-50 nagpapatakbo bawat 100 bola', '每 100 个球 40-50 次运行', '100 ಎಸೆತಗಳಿಗೆ 40-50 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 1, 'Between 30-39.99 runs per 100 balls', 'Between 30-39.99 runs per 100 balls', 'प्रति 100 गेंदों पर 30-39.99 रन के बीच', '100 બોલમાં દીઠ 30-39.99 વચ્ચે', 'Entre 30-39,99 pistes pour 100 balles', '30-39.99 এর মধ্যে 100 বল প্রতি রান', '30-39.99 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 30-39.99 ரன்கள் வரை', 'ระหว่าง 30-39.99 วิ่งต่อ 100 ลูก', -4, 0, 'STRIKE_RATE_30_3999', '', 'От 30 до 39,99 пробега на 100 мячей', 'Antara 30-39,99 lari per 100 bola', 'Sa pagitan ng 30-39.99 tumatakbo bawat 100 bola', '每 100 个球 30-39.99 次运行', '100 ಎಸೆತಗಳಿಗೆ 30-39.99 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 1, 'Below 30 runs per 100 balls', 'Below 30 runs per 100 balls', 'प्रति 100 गेंदों पर 30 रन से कम', '100 દડા દીઠ 30 રનથી નીચે', 'Moins de 30 pistes pour 100 balles', '100 বল প্রতি 30 রান নীচে', '100 ਦੌੜਾਂ ਪ੍ਰਤੀ 30 ਦੌੜਾਂ ਤੋਂ ਘੱਟ', '100 பந்துகளுக்கு 30 ரன்களுக்கு கீழே', 'ต่ำกว่า 30 วิ่งต่อ 100 ลูก', -6, 0, 'STRIKE_RATE_BELOW_30', '', 'Менее 30 пробежек на 100 мячей', 'Di bawah 30 run per 100 bola', 'Sa ibaba 30 tumatakbo bawat 100 bola', 'Менее 30 пробежек на 100 мячей', '100 ಎಸೆತಗಳಿಗೆ 30 ರನ್‌ಗಳ ಕೆಳಗೆ');";
    	$this->db->query($sql);

    	//Add Rules for T20
		$sql = "DELETE FROM ".$this->db->dbprefix(MASTER_SCORING_RULES)." WHERE `format` = 3 AND master_scoring_category_id IN (14,15,16,17);";
    	$this->db->query($sql);

    	$sql = "INSERT INTO ".$this->db->dbprefix(MASTER_SCORING_RULES)." (`master_scoring_category_id`, `format`, `score_position`, `en_score_position`, `hi_score_position`, `guj_score_position`, `fr_score_position`, `ben_score_position`, `pun_score_position`, `tam_score_position`, `th_score_position`, `score_points`, `points_unit`, `meta_key`, `meta_key_alias`, `ru_score_position`, `id_score_position`, `tl_score_position`, `zh_score_position`, `kn_score_position`) VALUES
		(14, 3, 'In announced lineups', 'In announced lineups', 'घोषित लाइनअप में', 'જાહેરાત કરેલ લાઇનઅપ્સમાં', 'Dans les files d\'attente annoncées', 'ঘোষিত লাইনআপগুলিতে', 'ਘੋਸ਼ਿਤ ਲਾਈਨਾਂ ਵਿੱਚ', 'அறிவிக்கப்பட்ட வரிசையில்', 'ในการประกาศรายชื่อผู้เล่นตัวจริง', 4, 0, 'STARTING_11', '', 'В заявленных составах', 'Dalam formasi yang diumumkan', 'Sa inilahad na mga lineup', '在公布的阵容中', 'ಘೋಷಿತ ತಂಡಗಳಲ್ಲಿ'),
		(14, 3, 'Run', 'Run', 'रन', 'ચલાવો', 'Cours', 'চালান', 'ਰਨ', 'ஓடு', 'วิ่ง', 1, 0, 'RUN', '', 'ЗАПУСТИТЬ', 'LARI', 'TUMATAKBO', '跑步', 'ಓಡು'),
		(14, 3, 'Wicket (Excluding Run Out)', 'Wicket Excluding Run Out', 'विकेट (रन आउट को छोड़कर)', 'વિકેટ (રન આઉટ સિવાય)', 'Wicket (à l\'exclusion de l\'épuisement)', 'উইকেট (রান আউট বাদে)', 'ਵਿਕਟ (ਰਨ ਆ Outਟ ਨੂੰ ਛੱਡ ਕੇ)', 'விக்கெட் (ரன் அவுட் தவிர)', 'ประตู (ไม่รวมหมด)', 25, 0, 'WICKET', '', 'Калитка (исключая выбег)', 'Gawang (Tidak Termasuk Kehabisan)', 'Wicket (Hindi kasama ang Naubos na)', '检票口（不包括用完）', 'ವಿಕೆಟ್ (ರನ್ Out ಟ್ ಹೊರತುಪಡಿಸಿ)'),
		(14, 3, 'Catch', 'Catch', 'कैच', 'કૅચસ', 'Attraper', 'ধরা', 'ਫੜੋ', 'பிடி', 'จับ', 8, 0, 'CATCH', '', 'Ловить', 'Menangkap', 'Mahuli', '抓住', 'ಕ್ಯಾಚ್'),
		(14, 3, 'Stumping', 'Stumping', 'स्टम्पिंग', 'સ્ટમપિંગ', 'Assommer', 'স্টাম্পিং', 'স্টাম্পিং', 'ஸ்டம்பிங்', 'ตอ', 12, 0, 'STUMPING', '', 'Stumping', 'Membingungkan', 'Nakaka-stump', '绊倒', 'ಸ್ಟಂಪಿಂಗ್'),
		(14, 3, 'Run out (Thrower)', 'Run out (Thrower)', 'रन​-आउट (फेंकने वाला)', 'રન આઉટ (ફેંકનાર)', 'Run out (lanceur)', 'রান আউট (নিক্ষিপ্ত)', 'ਰਨ ਆ outਟ (ਥ੍ਰੋਅਰ)', 'ரன் அவுட் (வீசுபவர்)', 'หมด (Thrower)', 6, 0, 'RUN_OUT_THROWER', '', 'Беги (Метатель)', 'Habis (Pelempar)', 'Naubusan (Magtapon)', '跑出（投掷者）', 'ರನ್ out ಟ್ (ಥ್ರೋವರ್)'),
		(14, 3, 'Run out (Catcher)', 'Run out (Catcher)', 'रन​-आउट (पकड़ने वाला)', 'રન આઉટ (કેચર)', 'Run out (receveur)', 'রান আউট (ক্যাচার)', 'ਰਨ ਆ outਟ (ਕੈਚਰ)', 'ரன் அவுட் (பற்றும்)', 'หมด (Catcher)', 6, 0, 'RUN_OUT_CATCHER', '', 'Беги (Catcher)', 'Habis (Penangkap)', 'Naubusan (Catcher)', '跑出（捕手）', 'ರನ್ out ಟ್ (ಕ್ಯಾಚರ್)'),
		(14, 3, 'Run out (Direct hit)', 'Run out (Direct hit)', 'रन आउट (डायरेक्ट हिट)', 'રન આઉટ (સીધી હિટ)', 'Run out (coup direct)', 'রান আউট (সরাসরি আঘাত)', 'ਰਨ ਆ outਟ (ਸਿੱਧੀ ਹਿੱਟ)', 'ரன் அவுட் (நேரடி வெற்றி)', 'หมด (ตีโดยตรง)', 12, 0, 'RUN_OUT_DIRECT_HIT', '', 'Бежать (прямое попадание)', 'Habis (Tembak langsung)', 'Naubusan (Direktang hit)', '跑出（直接命中）', 'ರನ್ out ಟ್ (ಡೈರೆಕ್ಟ್ ಹಿಟ್)'),
		(14, 3, 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'शून्य  पर आउट (बल्लेबाज, विकेटकीपर और ऑलराउंडर)', 'શૂન્ય માટે બરતરફ (બેટ્સમેન, વિકેટ-કીપર અને ઓલ-રાઉન્ડર)', 'Licenciement pour un zéro (Batsman, Wicket-Keeper & All-Rounder)', 'শূন্যের জন্য বরখাস্ত (ব্যাটসম্যান, উইকেট-কিপার এবং অল-রাউন্ডার)', 'ਸਿਫ਼ਰ (ਬੈਟਸਮੈਨ, ਵਿਕਟ ਕੀਪਰ ਅਤੇ ਆਲ-ਰਾ Rਂਡਰ) ਲਈ ਬਰਖਾਸਤਗੀ', 'பூஜ்ஜியத்திற்கான தள்ளுபடி (பேட்ஸ்மேன், விக்கெட் கீப்பர் & ஆல்-ரவுண்டர்)', 'การไล่ออกเป็นศูนย์ (Batsman, Wicket-Keeper & All-Rounder)', -2, 0, 'DUCK', '', 'Увольнение за утку (Бэтсмен, Хранитель калитки и Универсал)', 'Pemberhentian untuk bebek (Batsman, Penjaga Gawang & All-Rounder)', 'Pag-alis para sa isang pato (Batsman, Wicket-Keeper & All-Rounder)', '解雇鸭子（击球手，守门员和全能者）', 'ಶೂನ್ಯಕ್ಕೆ ವಜಾಗೊಳಿಸುವುದು (ಬ್ಯಾಟ್ಸ್‌ಮನ್, ವಿಕೆಟ್ ಕೀಪರ್ ಮತ್ತು ಆಲ್-ರೌಂಡರ್)'),
		(15, 3, 'Boundary Bonus', 'Boundary Bonus', 'सीमा बोनस', 'બાઉન્ડ્રી બોનસ', 'Bonus de limite', 'বাউন্ডারি বোনাস', 'ਸੀਮਾ ਬੋਨਸ', 'எல்லை போனஸ்', 'โบนัสขอบเขต', 1, 0, 'FOUR', '', 'Граничный бонус', 'Bonus Batas', 'Boundary Bonus', '边界奖金', 'ಗಡಿ ಬೋನಸ್'),
		(15, 3, 'Six Bonus', 'Six Bonus', 'छह बोनस', 'છ બોનસ', 'Six bonus', 'ছয় বোনাস', 'ਛੇ ਬੋਨਸ', 'ஆறு போனஸ்', 'หกโบนัส', 2, 0, 'SIX', '', 'Шесть бонусов', 'Enam Bonus', 'Anim na Bonus', '六分红', 'ಆರು ಬೋನಸ್'),
		(15, 3, '30 run Bonus', '30 run Bonus', '30 रन बोनस', '30 રન બોનસ', 'Bonus de 30 courses', '30 রান বোনাস', '30 ਚਲਾਓ ਬੋਨਸ', '30 ரன் போனஸ்', 'โบนัสวิ่ง 30', 4, 0, '30_BONUS', '', 'Бонус за 30 пробежек', '30 kali bonus', '30 run Bonus', '30 次运行奖励', '30 ರನ್ ಬೋನಸ್'),
		(15, 3, 'Half-century Bonus ', 'Half-century Bonus ', 'अर्धशतक बोनस', 'અડધી સદીનો બોનસ', 'Bonus dun demi-siècle', 'অর্ধ শতাব্দীর বোনাস', 'ਅੱਧੀ ਸਦੀ ਦਾ ਬੋਨਸ', 'அரை நூற்றாண்டு போனஸ்', 'โบนัสครึ่งศตวรรษ', 8, 0, 'HALF_CENTURY', '', 'Бонус за полвека', 'Bonus setengah abad', 'Half-siglo Bonus', '半个世纪奖金', 'ಅರ್ಧ ಶತಮಾನದ ಬೋನಸ್'),
		(15, 3, 'Century Bonus', 'Century Bonus', 'शतक बोनस', 'સદી બોનસ', 'Bonus du siècle', 'সেঞ্চুরি বোনাস', 'ਸਦੀ ਬੋਨਸ', 'நூற்றாண்டு போனஸ்', 'โบนัสศตวรรษ', 16, 0, 'CENTURY', '', 'Бонус века', 'Bonus Abad', 'Bonus sa Siglo', '世纪红利', 'ಸೆಂಚುರಿ ಬೋನಸ್'),
		(15, 3, 'Maiden over', 'Maiden over', 'मेडेन ओवर', 'મેઇડન ઓવર', 'Maiden sur', 'মেয়ের উপর', 'ਕੁਆਰੀ ਹੋ ਗਈ', 'மெய்டன் ஓவர்', 'หญิงสาวมากกว่า', 12, 0, 'MAIDEN_OVER', '', 'Дева закончилась', 'Gadis atas', 'Pagdalaga ng dalaga', '处女过', 'ಮೇಡನ್ ಓವರ್'),
		(15, 3, '3 Catch Bonus', '3 Catch Bonus', '3 कैच बोनस', '3 બોનસ બો', '3 Bonus de capture', '3 ক্যাচ বোনাস', '3 ਕੈਚ ਬੋਨਸ', '3 கேட்ச் போனஸ்', '3 จับโบนัส', 4, 0, 'CATCH_3', '', '3 Бонус улова', '3 Bonus Tangkapan', '3 Makibalita Bonus', '3 捕获奖金', '3 ಕ್ಯಾಚ್ ಬೋನಸ್'),
		(15, 3, '3 Wicket Bonus', '3 Wicket Bonus', '3 विकेट बोनस', '3 વિકેટ બોનસ', 'Bonus de 3 guichets', '3 উইকেট বোনাস', '3 ਵਿਕਟ ਬੋਨਸ', '3 விக்கெட் போனஸ்', 'โบนัส 3 ประตู', 4, 0, 'THREE_WICKET', '', '3 Бонус калитки', 'Bonus 3 Gawang', '3 Bonus sa Wicket', '3 检票奖金', '3 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 3, '4 Wicket Bonus', '4 Wicket Bonus', '4 विकेट बोनस', '4 વિકેટ બોનસ', 'Bonus de 4 guichets', '4 উইকেট বোনাস', '4 ਵਿਕਟ ਬੋਨਸ', '4 விக்கெட் போனஸ்', 'โบนัส 4 ประตู', 8, 0, 'FOUR_WICKET', '', '4 Бонус калитки', 'Bonus 4 Gawang', '4 Bonus sa Wicket', '4 检票奖金', '4 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 3, '5 Wicket Bonus', '5 Wicket Bonus', '5 विकेट बोनस', '5 વિકેટ બોનસ', 'Bonus de 5 guichets', '5 উইকেট বোনাস', '5 ਵਿਕਟ ਬੋਨਸ', '5 விக்கெட் போனஸ்', 'โบนัส 5 ประตู', 16, 0, 'FIVE_WICKET', '', '5 Бонус калитки', 'Bonus 5 Gawang', '5 Bonus sa Wicket', '5 检票奖金', '5 ವಿಕೆಟ್ ಬೋನಸ್'),
		(15, 3, 'Bonus (LBW / Bowled)', 'Bonus (LBW / Bowled)', 'बोनस (एलबीडब्ल्यू / बोल्ड)', 'બોનસ (એલબીડબલ્યુ / બાઉલ્ડ)', 'Bonus (LBW / Bowled)', 'বোনাস (এলবিডাব্লু / বোল্ড)', 'ਬੋਨਸ (ਐਲਬੀਡਬਲਯੂ / ਬੋਲਡ)', 'போனஸ் (எல்.பி.டபிள்யூ / பவுல்ட்)', 'โบนัส (ปอนด์ / โบว์ลิ่ง)', 8, 0, 'LBW_BOWLED', '', 'Бонус (LBW / Bowled)', 'Bonus (BBLR / Mabuk)', 'Bonus (LBW / Bowled)', '奖金（LBW / 保龄球）', 'ಬೋನಸ್ (ಎಲ್ಬಿಡಬ್ಲ್ಯೂ / ಬೌಲ್ಡ್)'),
		(16, 3, 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'ओवर की संख्या जिस्के ऊपर​ स्कोरिंग नियम लागू होंगे', 'ઇકોનોમી રેટ માટે નીચેના નિયમોની ગણતરી માટે બોલ્ડ કરવા માટે ન્યૂનતમ ઓવર', 'Nombre minimum de overs à jouer pour calculer les règles ci-dessous pour le tarif économique', 'অর্থনীতি হারের নিয়ম নীচে গণনা করার জন্য বোল করা ন্যূনতম সংখ্যা ওভার', 'ਆਰਥਿਕਤਾ ਦਰ ਲਈ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਓਵਰਾਂ ਦੀ ਗਿਣਤੀ', 'பொருளாதார வீதத்திற்கான விதிகளை கீழே கணக்கிடுவதற்கு பந்து வீச வேண்டிய குறைந்தபட்ச ஓவர்கள்', 'จำนวนขั้นต่ำที่จะโค้งคำนับสำหรับการคำนวณด้านล่างกฎสำหรับอัตราประหยัด', 2, 0, 'MINIMUM_BOWLING_BOWLED_OVER', '', 'Минимальное количество оверов для игры в боулинг для расчета следующих правил для экономичного тарифа', 'Jumlah minimum over yang harus di-bow untuk menghitung di bawah aturan untuk Tarif Ekonomi', 'Min bilang ng mga sobra sa bowled para makalkula sa ibaba ang mga patakaran para sa Economy Rate', '用于计算以下经济率规则的最少投球次数', 'ಎಕಾನಮಿ ದರಕ್ಕಾಗಿ ನಿಯಮಗಳನ್ನು ಕೆಳಗೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಬೌಲ್ ಮಾಡಲು ಕನಿಷ್ಠ ಸಂಖ್ಯೆಯ ಓವರ್‌ಗಳು'),
		(16, 3, 'Below 5 runs per over', 'Below 5 runs per over', '5 रन प्रति ओवर से नीचे', '5 ઓવર દીઠ રન', 'Moins de 5 courses par plus', 'ওভার প্রতি 5 রান', '5 ਓਵਰਾਂ ਦੇ ਹੇਠਾਂ', 'ஒரு ஓவருக்கு 5 ரன்களுக்கு கீழே', 'ต่ำกว่า 5 รันต่อโอเวอร์', 6, 0, 'ECONOMY_BELOW_5', '', 'Менее 5 пробежек за овер', 'Di bawah 5 run per over', 'Sa ibaba ng 5 tumatakbo bawat higit', '每回合低于 5 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 5 ರನ್‌ಗಳ ಕೆಳಗೆ'),
		(16, 3, 'Between 5-5.99 runs per over', 'Between 5-5.99 runs per over', '5-5.99 रन प्रति ओवर के बीच', '5-5.99 વચ્ચે પ્રતિ ઓવર', 'Entre 5 et 5,99 courses par over', '5-5.99 এর মধ্যে ওভার প্রতি রান', '5-5.99 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 5 முதல் 5.99 ரன்கள் வரை', 'ระหว่าง 5-5.99 รันต่อโอเวอร์', 4, 0, 'ECONOMY_5_599', '', 'От 5 до 5,99 пробежек за овер', 'Antara 5-5,99 run per over', 'Sa pagitan ng 5-5.99 ay tumatakbo bawat higit', '每次超过 5-5.99 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 5-5.99 ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 3, 'Between 6-7 runs per over', 'Between 6-7 runs per over', '6-7 रन प्रति ओवर के बीच', '6-7 વચ્ચે પ્રતિ ઓવર', 'Entre 6 et 7 courses par over', '6-7 এর মধ্যে ওভার প্রতি রান', '6-7 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 6 முதல் 7 ரன்கள் வரை', 'ระหว่าง 6-7 รันต่อโอเวอร์', 2, 0, 'ECONOMY_6_7', '', 'От 6 до 7 пробежек за повтор', 'Antara 6-7 run per over', 'Sa pagitan ng 6-7 tumatakbo bawat higit', '每次超过 6-7 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 6-7 ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 3, 'Between 10-11 runs per over', 'Between 10-11 runs per over', '10-11 रन प्रति ओवर के बीच', '10-11  વચ્ચે પ્રતિ ઓવર', 'Entre 10 et 11 courses par over', '10-11 এর মধ্যে ওভার প্রতি রান', '10-11  ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 10 முதல் 11 ரன்கள் வரை', 'ระหว่าง 10-11  รันต่อโอเวอร์', -2, 0, 'ECONOMY_10_11', '', 'От 10 до 11 пробежек за переезд', 'Antara 10-11 run per over', 'Sa pagitan ng 10-11 tumatakbo bawat higit sa', '每回合 10-11 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 10-11  ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 3, 'Between 11.01-12 runs per over', 'Between 11.01-12 runs per over', '11.01-12 रन प्रति ओवर के बीच', '11.01-12 વચ્ચે પ્રતિ ઓવર', 'Entre 11,01 et 12 courses par over', '11.01-12 এর মধ্যে ওভার প্রতি রান', '11.01-12 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 11.01 முதல் 12 ரன்கள் வரை', 'ระหว่าง 11.01-12 รันต่อโอเวอร์', -4, 0, 'ECONOMY_1101_12', '', 'С 11.01 по 12 запусков за овер', 'Antara 11,01-12 run per over', 'Sa pagitan ng 11.01-12 tumatakbo bawat higit', '每轮 11.01-12 次之间', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 11.01-12 ರನ್‌ಗಳ ನಡುವೆ'),
		(16, 3, 'Above 12 runs per over', 'Above 12 runs per over', '12 रन प्रति ओवर से ऊपर', '12 ઓવર દીઠ રન', 'Au-dessus de 12 courses par over', 'ওভার প্রতি 12 রান উপরে', '12 ਓਵਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 12 ரன்களுக்கு மேல்', 'สูงกว่า 12 รันต่อโอเวอร์', -6, 0, 'ECONOMY_ABOVE_12', '', 'Свыше 12 пробежек за овер', 'Di atas 12 run per over', 'Sa itaas 12 tumatakbo bawat higit sa', '每回合超过 12 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 12 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
		(17, 3, 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'स्ट्राइक रेट के लिए नीचे दिए गए नियमों की गणना के लिए खेली जाने वाली गेंदों की न्यूनतम संख्या (गेंदबाज को छोड़कर)', 'સ્ટ્રાઈક રેટ (બાઉલર સિવાય) ની નીચેના નિયમોની ગણતરી કરવા માટે રમવાના બોલમાંનો મીન નંબર', 'Nombre minimum de balles à jouer pour calculer les règles ci-dessous pour le taux de grève (sauf le quilleur)', 'স্ট্রাইক রেট (বোলার ব্যতীত) নীচের নিয়মের নিচে গণনা করার জন্য ন্যূনতম বল খেলতে হবে', 'ਸਟਰਾਈਕ ਰੇਟ (ਬਾ rulesਲਰ ਨੂੰ ਛੱਡ ਕੇ) ਦੇ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਗੇਂਦਾਂ ਖੇਡੀਆਂ ਜਾਣਗੀਆਂ.', 'ஸ்ட்ரைக் வீதத்திற்கான விதிகளை கீழே கணக்கிட (பந்துவீச்சாளரைத் தவிர) விளையாட வேண்டிய குறைந்தபட்ச பந்துகள்', 'จำนวนลูกขั้นต่ำที่จะเล่นเพื่อคำนวณกฎด้านล่างสำหรับอัตราการตี (ยกเว้นกะลา)', 10, 0, 'MINIMUM_BALL_PLAYED', '', 'Минимальное количество шаров, которые должны быть сыграны для расчета приведенных ниже правил для ставки страйка (кроме боулера)', 'Jumlah minimum bola yang akan dimainkan untuk menghitung di bawah aturan untuk Strike Rate (Kecuali Bowler)', 'Min hindi ng mga bola na dapat i-play para makalkula ang mga patakaran sa ibaba para sa Strike Rate (Maliban sa Bowler)', '计算以下击球率规则的最少球数（保龄球除外）', 'ಸ್ಟ್ರೈಕ್ ರೇಟ್ (ಬೌಲರ್ ಹೊರತುಪಡಿಸಿ) ಗಾಗಿ ಕೆಳಗಿನ ನಿಯಮಗಳನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಆಡಬೇಕಾದ ಕನಿಷ್ಠ ಚೆಂಡುಗಳು'),
		(17, 3, 'Above 170 runs per 100 balls', 'Above 170 runs per 100 balls', 'प्रति 100 गेंदों पर 170 रन से ऊपर', '100 દડામાં 170 રનથી વધુ', 'Au-dessus de 170 pistes pour 100 balles', '100 বল প্রতি 170 রান উপরে', '170 ਦੌੜਾਂ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 170 ரன்களுக்கு மேல்', 'สูงกว่า 170 วิ่งต่อ 100 ลูก', 6, 0, 'STRIKE_RATE_ABOVE_170', '', 'Свыше 170 пробегов на 100 мячей', 'Di atas 170 lari per 100 bola', 'Sa itaas 170 tumatakbo bawat 100 bola', '每 100 个球 170 次以上', '100 ಎಸೆತಗಳಿಗೆ 170 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
		(17, 3, 'Between 150.01-170 runs per 100 balls', 'Between 150.01-170 runs per 100 balls', 'प्रति 100 गेंदों पर 150.01-170 रन के बीच', '100 બોલમાં દીઠ 150.01-170 વચ્ચે', 'Entre 150,01-170 pistes pour 100 balles', '150.01-170 এর মধ্যে 100 বল প্রতি রান', '150.01-170 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 150.01-170 ரன்கள் வரை', 'ระหว่าง 150.01-170 วิ่งต่อ 100 ลูก', 4, 0, 'STRIKE_RATE_15001_170', '', '150,01-170 пробежек на 100 мячей', 'Antara 150,01-170 lari per 100 bola', 'Sa pagitan ng 150.01-170 nagpapatakbo bawat 100 bola', '每 100 个球 150.01-170 次运行之间', '100 ಎಸೆತಗಳಿಗೆ 150.01-170 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 3, 'Between 130-150 runs per 100 balls', 'Between 130-150 runs per 100 balls', 'प्रति 100 गेंदों पर 130-150 रन के बीच', '100 બોલમાં દીઠ 1130-150 વચ્ચે', 'Entre 130-150 pistes pour 100 balles', '130-150 এর মধ্যে 100 বল প্রতি রান', '130-150 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 130-150 ரன்கள் வரை', 'ระหว่าง 130-150 วิ่งต่อ 100 ลูก', 2, 0, 'STRIKE_RATE_130_150', '', '130-150 пробежек на 100 мячей', 'Antara 130-150 lari per 100 bola', 'Sa pagitan ng 130-150 tumatakbo bawat 100 bola', '每 100 个球 130-150 次运行', '100 ಎಸೆತಗಳಿಗೆ 130-150 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 3, 'Between 60-70 runs per 100 balls', 'Between 60-70 runs per 100 balls', 'प्रति 100 गेंदों पर 60-70 रन के बीच', '100 બોલમાં દીઠ 60-70 વચ્ચે', 'Entre 60-70 pistes pour 100 balles', '60-70 এর মধ্যে 100 বল প্রতি রান', '60-70 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 60-70 ரன்கள் வரை', 'ระหว่าง 60-70 วิ่งต่อ 100 ลูก', -2, 0, 'STRIKE_RATE_60_70', '', 'От 60 до 70 пробежек на 100 мячей.', 'Antara 60-70 run per 100 bola', 'Sa pagitan ng 60-70 nagpapatakbo bawat 100 bola', '每 100 个球 60-70 次运行', '100 ಎಸೆತಗಳಿಗೆ 60-70 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 3, 'Between 50-59.99 runs per 100 balls', 'Between 50-59.99 runs per 100 balls', 'प्रति 100 गेंदों पर 50-59.99 रन के बीच', '100 બોલમાં દીઠ 50-59.99 વચ્ચે', 'Entre 50-59,99 pistes pour 100 balles', '50-59.99 এর মধ্যে 100 বল প্রতি রান', '50-59.99 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 50-59.99 ரன்கள் வரை', 'ระหว่าง 50-59.99 วิ่งต่อ 100 ลูก', -4, 0, 'STRIKE_RATE_50_5999', '', 'От 50 до 59,99 пробега на 100 мячей', 'Antara 50-59,99 lari per 100 bola', 'Sa pagitan ng 50-59.99 tumatakbo bawat 100 bola', '每 100 个球运行 50-59.99 次', '100 ಎಸೆತಗಳಿಗೆ 50-59.99 ರನ್‌ಗಳ ನಡುವೆ'),
		(17, 3, 'Below 50 runs per 100 balls', 'Below 50 runs per 100 balls', 'प्रति 100 गेंदों पर 50 रन से कम', '100 દડા દીઠ 50 રનથી નીચે', 'Moins de 50 pistes pour 100 balles', '100 বল প্রতি 50 রান নীচে', '100 ਦੌੜਾਂ ਪ੍ਰਤੀ 50 ਦੌੜਾਂ ਤੋਂ ਘੱਟ', '100 பந்துகளுக்கு 50 ரன்களுக்கு கீழே', 'ต่ำกว่า 50 วิ่งต่อ 100 ลูก', -6, 0, 'STRIKE_RATE_BELOW_50', '', 'Менее 50 пробежек на 100 мячей', 'Di bawah 50 run per 100 bola', 'Sa ibaba ng 50 ay tumatakbo bawat 100 bola', '每 100 个球 50 次以下', '100 ಎಸೆತಗಳಿಗೆ 50 ರನ್‌ಗಳ ಕೆಳಗೆ');";
	    $this->db->query($sql);

	    //Add Rules for T10
		$sql = "DELETE FROM ".$this->db->dbprefix(MASTER_SCORING_RULES)." WHERE `format` = 4 AND master_scoring_category_id IN (14,15,16,17);";
    	$this->db->query($sql);
		$sql = "INSERT INTO ".$this->db->dbprefix(MASTER_SCORING_RULES)." (`master_scoring_category_id`, `format`, `score_position`, `en_score_position`, `hi_score_position`, `guj_score_position`, `fr_score_position`, `ben_score_position`, `pun_score_position`, `tam_score_position`, `th_score_position`, `score_points`, `points_unit`, `meta_key`, `meta_key_alias`, `ru_score_position`, `id_score_position`, `tl_score_position`, `zh_score_position`, `kn_score_position`) VALUES
			(14, 4, 'In announced lineups', 'In announced lineups', 'घोषित लाइनअप में', 'જાહેરાત કરેલ લાઇનઅપ્સમાં', 'Dans les files d\'attente annoncées', 'ঘোষিত লাইনআপগুলিতে', 'ਘੋਸ਼ਿਤ ਲਾਈਨਾਂ ਵਿੱਚ', 'அறிவிக்கப்பட்ட வரிசையில்', 'ในการประกาศรายชื่อผู้เล่นตัวจริง', 4, 0, 'STARTING_11', '', 'В заявленных составах', 'Dalam formasi yang diumumkan', 'Sa inilahad na mga lineup', '在公布的阵容中', 'ಘೋಷಿತ ತಂಡಗಳಲ್ಲಿ'),
			(14, 4, 'Run', 'Run', 'रन', 'ચલાવો', 'Cours', 'চালান', 'ਰਨ', 'ஓடு', 'วิ่ง', 1, 0, 'RUN', '', 'ЗАПУСТИТЬ', 'LARI', 'TUMATAKBO', '跑步', 'ಓಡು'),
			(14, 4, 'Wicket (Excluding Run Out)', 'Wicket Excluding Run Out', 'विकेट (रन आउट को छोड़कर)', 'વિકેટ (રન આઉટ સિવાય)', 'Wicket (à l\'exclusion de l\'épuisement)', 'উইকেট (রান আউট বাদে)', 'ਵਿਕਟ (ਰਨ ਆ Outਟ ਨੂੰ ਛੱਡ ਕੇ)', 'விக்கெட் (ரன் அவுட் தவிர)', 'ประตู (ไม่รวมหมด)', 25, 0, 'WICKET', '', 'Калитка (исключая выбег)', 'Gawang (Tidak Termasuk Kehabisan)', 'Wicket (Hindi kasama ang Naubos na)', '检票口（不包括用完）', 'ವಿಕೆಟ್ (ರನ್ Out ಟ್ ಹೊರತುಪಡಿಸಿ)'),
			(14, 4, 'Catch', 'Catch', 'कैच', 'કૅચસ', 'Attraper', 'ধরা', 'ਫੜੋ', 'பிடி', 'จับ', 8, 0, 'CATCH', '', 'Ловить', 'Menangkap', 'Mahuli', '抓住', 'ಕ್ಯಾಚ್'),
			(14, 4, 'Stumping', 'Stumping', 'स्टम्पिंग', 'સ્ટમપિંગ', 'Assommer', 'স্টাম্পিং', 'স্টাম্পিং', 'ஸ்டம்பிங்', 'ตอ', 12, 0, 'STUMPING', '', 'Stumping', 'Membingungkan', 'Nakaka-stump', '绊倒', 'ಸ್ಟಂಪಿಂಗ್'),
			(14, 4, 'Run out (Thrower)', 'Run out (Thrower)', 'रन​-आउट (फेंकने वाला)', 'રન આઉટ (ફેંકનાર)', 'Run out (lanceur)', 'রান আউট (নিক্ষিপ্ত)', 'ਰਨ ਆ outਟ (ਥ੍ਰੋਅਰ)', 'ரன் அவுட் (வீசுபவர்)', 'หมด (Thrower)', 6, 0, 'RUN_OUT_THROWER', '', 'Беги (Метатель)', 'Habis (Pelempar)', 'Naubusan (Magtapon)', '跑出（投掷者）', 'ರನ್ out ಟ್ (ಥ್ರೋವರ್)'),
			(14, 4, 'Run out (Catcher)', 'Run out (Catcher)', 'रन​-आउट (पकड़ने वाला)', 'રન આઉટ (કેચર)', 'Run out (receveur)', 'রান আউট (ক্যাচার)', 'ਰਨ ਆ outਟ (ਕੈਚਰ)', 'ரன் அவுட் (பற்றும்)', 'หมด (Catcher)', 6, 0, 'RUN_OUT_CATCHER', '', 'Беги (Catcher)', 'Habis (Penangkap)', 'Naubusan (Catcher)', '跑出（捕手）', 'ರನ್ out ಟ್ (ಕ್ಯಾಚರ್)'),
			(14, 4, 'Run out (Direct hit)', 'Run out (Direct hit)', 'रन आउट (डायरेक्ट हिट)', 'રન આઉટ (સીધી હિટ)', 'Run out (coup direct)', 'রান আউট (সরাসরি আঘাত)', 'ਰਨ ਆ outਟ (ਸਿੱਧੀ ਹਿੱਟ)', 'ரன் அவுட் (நேரடி வெற்றி)', 'หมด (ตีโดยตรง)', 12, 0, 'RUN_OUT_DIRECT_HIT', '', 'Бежать (прямое попадание)', 'Habis (Tembak langsung)', 'Naubusan (Direktang hit)', '跑出（直接命中）', 'ರನ್ out ಟ್ (ಡೈರೆಕ್ಟ್ ಹಿಟ್)'),
			(14, 4, 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'Dismissal for a duck ( Batsman, Wicket-Keeper & All-Rounder)', 'शून्य  पर आउट (बल्लेबाज, विकेटकीपर और ऑलराउंडर)', 'શૂન્ય માટે બરતરફ (બેટ્સમેન, વિકેટ-કીપર અને ઓલ-રાઉન્ડર)', 'Licenciement pour un zéro (Batsman, Wicket-Keeper & All-Rounder)', 'শূন্যের জন্য বরখাস্ত (ব্যাটসম্যান, উইকেট-কিপার এবং অল-রাউন্ডার)', 'ਸਿਫ਼ਰ (ਬੈਟਸਮੈਨ, ਵਿਕਟ ਕੀਪਰ ਅਤੇ ਆਲ-ਰਾ Rਂਡਰ) ਲਈ ਬਰਖਾਸਤਗੀ', 'பூஜ்ஜியத்திற்கான தள்ளுபடி (பேட்ஸ்மேன், விக்கெட் கீப்பர் & ஆல்-ரவுண்டர்)', 'การไล่ออกเป็นศูนย์ (Batsman, Wicket-Keeper & All-Rounder)', -2, 0, 'DUCK', '', 'Увольнение за утку (Бэтсмен, Хранитель калитки и Универсал)', 'Pemberhentian untuk bebek (Batsman, Penjaga Gawang & All-Rounder)', 'Pag-alis para sa isang pato (Batsman, Wicket-Keeper & All-Rounder)', '解雇鸭子（击球手，守门员和全能者）', 'ಶೂನ್ಯಕ್ಕೆ ವಜಾಗೊಳಿಸುವುದು (ಬ್ಯಾಟ್ಸ್‌ಮನ್, ವಿಕೆಟ್ ಕೀಪರ್ ಮತ್ತು ಆಲ್-ರೌಂಡರ್)'),
			(15, 4, 'Boundary Bonus', 'Boundary Bonus', 'सीमा बोनस', 'બાઉન્ડ્રી બોનસ', 'Bonus de limite', 'বাউন্ডারি বোনাস', 'ਸੀਮਾ ਬੋਨਸ', 'எல்லை போனஸ்', 'โบนัสขอบเขต', 1, 0, 'FOUR', '', 'Граничный бонус', 'Bonus Batas', 'Boundary Bonus', '边界奖金', 'ಗಡಿ ಬೋನಸ್'),
			(15, 4, 'Six Bonus', 'Six Bonus', 'छह बोनस', 'છ બોનસ', 'Six bonus', 'ছয় বোনাস', 'ਛੇ ਬੋਨਸ', 'ஆறு போனஸ்', 'หกโบนัส', 2, 0, 'SIX', '', 'Шесть бонусов', 'Enam Bonus', 'Anim na Bonus', '六分红', 'ಆರು ಬೋನಸ್'),
			(15, 4, '30 run Bonus', '30 run Bonus', '30 रन बोनस', '30 રન બોનસ', 'Bonus de 30 courses', '30 রান বোনাস', '30 ਚਲਾਓ ਬੋਨਸ', '30 ரன் போனஸ்', 'โบนัสวิ่ง 30', 8, 0, '30_BONUS', '', 'Бонус за 30 пробежек', '30 kali bonus', '30 run Bonus', '30 次运行奖励', '30 ರನ್ ಬೋನಸ್'),
			(15, 4, 'Half-century Bonus ', 'Half-century Bonus ', 'अर्धशतक बोनस', 'અડધી સદીનો બોનસ', 'Bonus dun demi-siècle', 'অর্ধ শতাব্দীর বোনাস', 'ਅੱਧੀ ਸਦੀ ਦਾ ਬੋਨਸ', 'அரை நூற்றாண்டு போனஸ்', 'โบนัสครึ่งศตวรรษ', 16, 0, 'HALF_CENTURY', '', 'Бонус за полвека', 'Bonus setengah abad', 'Half-siglo Bonus', '半个世纪奖金', 'ಅರ್ಧ ಶತಮಾನದ ಬೋನಸ್'),
			(15, 4, 'Maiden over', 'Maiden over', 'मेडेन ओवर', 'મેઇડન ઓવર', 'Maiden sur', 'মেয়ের উপর', 'ਕੁਆਰੀ ਹੋ ਗਈ', 'மெய்டன் ஓவர்', 'หญิงสาวมากกว่า', 16, 0, 'MAIDEN_OVER', '', 'Дева закончилась', 'Gadis atas', 'Pagdalaga ng dalaga', '处女过', 'ಮೇಡನ್ ಓವರ್'),
			(15, 4, '3 Catch Bonus', '3 Catch Bonus', '3 कैच बोनस', '3 બોનસ બો', '3 Bonus de capture', '3 ক্যাচ বোনাস', '3 ਕੈਚ ਬੋਨਸ', '3 கேட்ச் போனஸ்', '3 จับโบนัส', 4, 0, 'CATCH_3', '', '3 Бонус улова', '3 Bonus Tangkapan', '3 Makibalita Bonus', '3 捕获奖金', '3 ಕ್ಯಾಚ್ ಬೋನಸ್'),
			(15, 4, '2 Wicket Bonus', '2 Wicket Bonus', '2 विकेट बोनस', '2 વિકેટ બોનસ', 'Bonus de 2 guichets', '2 উইকেট বোনাস', '2 ਵਿਕਟ ਬੋਨਸ', '2 விக்கெட் போனஸ்', 'โบนัส 2 ประตู', 8, 0, 'TWO_WICKET', '', '2 Бонус калитки', 'Bonus 2 Gawang', '2 Bonus sa Wicket', '2 检票奖金', '2 ವಿಕೆಟ್ ಬೋನಸ್'),
			(15, 4, '3 Wicket Bonus', '3 Wicket Bonus', '3 विकेट बोनस', '3 વિકેટ બોનસ', 'Bonus de 3 guichets', '3 উইকেট বোনাস', '3 ਵਿਕਟ ਬੋਨਸ', '3 விக்கெட் போனஸ்', 'โบนัส 3 ประตู', 16, 0, 'THREE_WICKET', '', '3 Бонус калитки', 'Bonus 3 Gawang', '3 Bonus sa Wicket', '3 检票奖金', '3 ವಿಕೆಟ್ ಬೋನಸ್'),
			(15, 4, 'Bonus (LBW / Bowled)', 'Bonus (LBW / Bowled)', 'बोनस (एलबीडब्ल्यू / बोल्ड)', 'બોનસ (એલબીડબલ્યુ / બાઉલ્ડ)', 'Bonus (LBW / Bowled)', 'বোনাস (এলবিডাব্লু / বোল্ড)', 'ਬੋਨਸ (ਐਲਬੀਡਬਲਯੂ / ਬੋਲਡ)', 'போனஸ் (எல்.பி.டபிள்யூ / பவுல்ட்)', 'โบนัส (ปอนด์ / โบว์ลิ่ง)', 8, 0, 'LBW_BOWLED', '', 'Бонус (LBW / Bowled)', 'Bonus (BBLR / Mabuk)', 'Bonus (LBW / Bowled)', '奖金（LBW / 保龄球）', 'ಬೋನಸ್ (ಎಲ್ಬಿಡಬ್ಲ್ಯೂ / ಬೌಲ್ಡ್)'),
			(16, 4, 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'Min number of overs to be bowled to calculate below rules for Economy Rate', 'ओवर की संख्या जिस्के ऊपर​ स्कोरिंग नियम लागू होंगे', 'ઇકોનોમી રેટ માટે નીચેના નિયમોની ગણતરી માટે બોલ્ડ કરવા માટે ન્યૂનતમ ઓવર', 'Nombre minimum de overs à jouer pour calculer les règles ci-dessous pour le tarif économique', 'অর্থনীতি হারের নিয়ম নীচে গণনা করার জন্য বোল করা ন্যূনতম সংখ্যা ওভার', 'ਆਰਥਿਕਤਾ ਦਰ ਲਈ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਓਵਰਾਂ ਦੀ ਗਿਣਤੀ', 'பொருளாதார வீதத்திற்கான விதிகளை கீழே கணக்கிடுவதற்கு பந்து வீச வேண்டிய குறைந்தபட்ச ஓவர்கள்', 'จำนวนขั้นต่ำที่จะโค้งคำนับสำหรับการคำนวณด้านล่างกฎสำหรับอัตราประหยัด', 1, 0, 'MINIMUM_BOWLING_BOWLED_OVER', '', 'Минимальное количество оверов для игры в боулинг для расчета следующих правил для экономичного тарифа', 'Jumlah minimum over yang harus di-bow untuk menghitung di bawah aturan untuk Tarif Ekonomi', 'Min bilang ng mga sobra sa bowled para makalkula sa ibaba ang mga patakaran para sa Economy Rate', '用于计算以下经济率规则的最少投球次数', 'ಎಕಾನಮಿ ದರಕ್ಕಾಗಿ ನಿಯಮಗಳನ್ನು ಕೆಳಗೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಬೌಲ್ ಮಾಡಲು ಕನಿಷ್ಠ ಸಂಖ್ಯೆಯ ಓವರ್‌ಗಳು'),
			(16, 4, 'Below 7 runs per over', 'Below 7 runs per over', '7 रन प्रति ओवर से नीचे', '7 ઓવર દીઠ રન', 'Moins de 7 courses par plus', 'ওভার প্রতি 7 রান', '7 ਓਵਰਾਂ ਦੇ ਹੇਠਾਂ', 'ஒரு ஓவருக்கு 7 ரன்களுக்கு கீழே', 'ต่ำกว่า 7 รันต่อโอเวอร์', 6, 0, 'ECONOMY_BELOW_7', '', 'Менее 7 пробежек за овер', 'Di bawah 7 run per over', 'Sa ibaba 7 ay tumatakbo bawat', '每回合低于 7 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 7 ರನ್‌ಗಳ ಕೆಳಗೆ'),
			(16, 4, 'Between 7-7.99 runs per over', 'Between 7-7.99 runs per over', '7-7.99 रन प्रति ओवर के बीच', '7-7.99 વચ્ચે પ્રતિ ઓવર', 'Entre 7 et 7,99 courses par over', '7-7.99 এর মধ্যে ওভার প্রতি রান', '7-7.99 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 7 முதல் 7.99 ரன்கள் வரை', 'ระหว่าง 7-7.99 รันต่อโอเวอร์', 4, 0, 'ECONOMY_7_799', '', 'От 7 до 7,99 пробежек за овер', 'Antara 7-7,99 run per over', 'Sa pagitan ng 7-7.99 tumatakbo bawat higit', '每次超过 7-7.99 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 7-7.99 ರನ್‌ಗಳ ನಡುವೆ'),
			(16, 4, 'Between 8-9 runs per over', 'Between 8-9 runs per over', '8-9 रन प्रति ओवर के बीच', '8-9 વચ્ચે પ્રતિ ઓવર', 'Entre 8 et 9 courses par over', '8-9 এর মধ্যে ওভার প্রতি রান', '8-9 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 8 முதல் 9 ரன்கள் வரை', 'ระหว่าง 8-9 รันต่อโอเวอร์', 2, 0, 'ECONOMY_8_9', '', 'От 8 до 9 пробежек за повтор', 'Antara 8-9 run per over', 'Sa pagitan ng 8-9 tumatakbo bawat higit', '每轮 8-9 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 8-9 ರನ್‌ಗಳ ನಡುವೆ'),
			(16, 4, 'Between 14-15 runs per over', 'Between 14-15 runs per over', '14-15 रन प्रति ओवर के बीच', '14-15  વચ્ચે પ્રતિ ઓવર', 'Entre 14 et 15 courses par over', '14-15 এর মধ্যে ওভার প্রতি রান', '14-15  ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 14 முதல் 15 ரன்கள் வரை', 'ระหว่าง 14-15  รันต่อโอเวอร์', -2, 0, 'ECONOMY_14_15', '', 'От 14 до 15 пробегов за повтор', 'Antara 14-15 run per over', 'Sa pagitan ng 14-15 tumatakbo bawat higit', '每回合 14-15 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 14-15  ರನ್‌ಗಳ ನಡುವೆ'),
			(16, 4, 'Between 15.01-16 runs per over', 'Between 15.01-16 runs per over', '15.01-16 रन प्रति ओवर के बीच', '15.01-16 વચ્ચે પ્રતિ ઓવર', 'Entre 15,01 et 16 courses par over', '15.01-16 এর মধ্যে ওভার প্রতি রান', '15.01-16 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 15.01 முதல் 16 ரன்கள் வரை', 'ระหว่าง 15.01-16 รันต่อโอเวอร์', -4, 0, 'ECONOMY_1501_16', '', 'С 15.01 по 16 запусков за овер', 'Antara 15,01-16 run per over', 'Sa pagitan ng 15.01-16 ay tumatakbo bawat higit', '每轮 15.01-16 次之间', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 15.01-16 ರನ್‌ಗಳ ನಡುವ'),
			(16, 4, 'Above 16 runs per over', 'Above 16 runs per over', '16 रन प्रति ओवर से ऊपर', '16 ઓવર દીઠ રન', 'Au-dessus de 16 courses par over', 'ওভার প্রতি 16 রান উপরে', '16 ਓਵਰ ਪ੍ਰਤੀ ਓਵਰ', 'ஒரு ஓவருக்கு 16 ரன்களுக்கு மேல்', 'สูงกว่า 16 รันต่อโอเวอร์', -6, 0, 'ECONOMY_ABOVE_16', '', 'Свыше 16 пробегов за овер', 'Di atas 16 run per over', 'Sa itaas 16 tumatakbo bawat higit sa', '每回合超过 16 次', 'ಪ್ರತಿ ಓವರ್‌ಗೆ 16 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
			(17, 4, 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'Min no of balls to be played to calculate below rules for Strike Rate (Except Bowler)', 'स्ट्राइक रेट के लिए नीचे दिए गए नियमों की गणना के लिए खेली जाने वाली गेंदों की न्यूनतम संख्या (गेंदबाज को छोड़कर)', 'સ્ટ્રાઈક રેટ (બાઉલર સિવાય) ની નીચેના નિયમોની ગણતરી કરવા માટે રમવાના બોલમાંનો મીન નંબર', 'Nombre minimum de balles à jouer pour calculer les règles ci-dessous pour le taux de grève (sauf le quilleur)', 'স্ট্রাইক রেট (বোলার ব্যতীত) নীচের নিয়মের নিচে গণনা করার জন্য ন্যূনতম বল খেলতে হবে', 'ਸਟਰਾਈਕ ਰੇਟ (ਬਾ rulesਲਰ ਨੂੰ ਛੱਡ ਕੇ) ਦੇ ਨਿਯਮਾਂ ਦੀ ਗਣਨਾ ਲਈ ਘੱਟੋ ਘੱਟ ਗੇਂਦਾਂ ਖੇਡੀਆਂ ਜਾਣਗੀਆਂ.', 'ஸ்ட்ரைக் வீதத்திற்கான விதிகளை கீழே கணக்கிட (பந்துவீச்சாளரைத் தவிர) விளையாட வேண்டிய குறைந்தபட்ச பந்துகள்', 'จำนวนลูกขั้นต่ำที่จะเล่นเพื่อคำนวณกฎด้านล่างสำหรับอัตราการตี (ยกเว้นกะลา)', 5, 0, 'MINIMUM_BALL_PLAYED', '', 'Минимальное количество шаров, которые должны быть сыграны для расчета приведенных ниже правил для ставки страйка (кроме боулера)', 'Jumlah minimum bola yang akan dimainkan untuk menghitung di bawah aturan untuk Strike Rate (Kecuali Bowler)', 'Min hindi ng mga bola na dapat i-play para makalkula ang mga patakaran sa ibaba para sa Strike Rate (Maliban sa Bowler)', '计算以下击球率规则的最少球数（保龄球除外）', 'ಸ್ಟ್ರೈಕ್ ರೇಟ್ (ಬೌಲರ್ ಹೊರತುಪಡಿಸಿ) ಗಾಗಿ ಕೆಳಗಿನ ನಿಯಮಗಳನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಆಡಬೇಕಾದ ಕನಿಷ್ಠ ಚೆಂಡುಗಳು'),
			(17, 4, 'Above 190 runs per 100 balls', 'Above 190 runs per 100 balls', 'प्रति 100 गेंदों पर 190 रन से ऊपर', '100 દડામાં 190 રનથી વધુ', 'Au-dessus de 190 pistes pour 100 balles', '100 বল প্রতি 190 রান উপরে', '190 ਦੌੜਾਂ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 190 ரன்களுக்கு மேல்', 'สูงกว่า 190 วิ่งต่อ 100 ลูก', 6, 0, 'STRIKE_RATE_ABOVE_190', '', 'Свыше 190 пробежек на 100 мячей', 'Di atas 190 run per 100 bola', 'Sa itaas 190 tumatakbo bawat 100 bola', '每 100 个球 190 次以上', '100 ಎಸೆತಗಳಿಗೆ 190 ರನ್‌ಗಳಿಗಿಂತ ಹೆಚ್ಚು'),
			(17, 4, 'Between 170.01-190 runs per 100 balls', 'Between 170.01-190 runs per 100 balls', 'प्रति 100 गेंदों पर 170.01-190 रन के बीच', '100 બોલમાં દીઠ 170.01-190 વચ્ચે', 'Entre 170,01-190 pistes pour 100 balles', '170.01-190 এর মধ্যে 100 বল প্রতি রান', '170.01-190 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 170.01-190 ரன்கள் வரை', 'ระหว่าง 170.01-190 วิ่งต่อ 100 ลูก', 4, 0, 'STRIKE_RATE_17001_190', '', '170,01-190 пробежек на 100 мячей', 'Antara 170,01-190 lari per 100 bola', 'Sa pagitan ng 170.01-190 ay tumatakbo bawat 100 bola', '每 100 个球 170.01-190 次运行', '100 ಎಸೆತಗಳಿಗೆ 170.01-190 ರನ್‌ಗಳ ನಡುವೆ'),
			(17, 4, 'Between 150-170 runs per 100 balls', 'Between 150-170 runs per 100 balls', 'प्रति 100 गेंदों पर 150-170 रन के बीच', '100 બોલમાં દીઠ 150-170 વચ્ચે', 'Entre 150-170 pistes pour 100 balles', '150-170 এর মধ্যে 100 বল প্রতি রান', '150-170 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 150-170 ரன்கள் வரை', 'ระหว่าง 150-170 วิ่งต่อ 100 ลูก', 2, 0, 'STRIKE_RATE_150_170', '', '150-170 пробежек на 100 мячей', 'Antara 150-170 lari per 100 bola', 'Sa pagitan ng 150-170 tumatakbo bawat 100 bola', '每 100 个球 150-170 次运行', '100 ಎಸೆತಗಳಿಗೆ 150-170 ರನ್‌ಗಳ ನಡುವೆ'),
			(17, 4, 'Between 70-80 runs per 100 balls', 'Between 70-80 runs per 100 balls', 'प्रति 100 गेंदों पर 70-80 रन के बीच', '100 બોલમાં દીઠ 70-80 વચ્ચે', 'Entre 70-80 pistes pour 100 balles', '70-80 এর মধ্যে 100 বল প্রতি রান', '70-80 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 70-80 ரன்கள் வரை', 'ระหว่าง 70-80 วิ่งต่อ 100 ลูก', -2, 0, 'STRIKE_RATE_70_80', '', 'От 70 до 80 пробежек на 100 мячей', 'Antara 70-80 run per 100 bola', 'Sa pagitan ng 70-80 tumatakbo bawat 100 bola', '每 100 个球 70-80 次运行', '100 ಎಸೆತಗಳಿಗೆ 70-80 ರನ್‌ಗಳ ನಡುವೆ'),
			(17, 4, 'Between 60-69.99 runs per 100 balls', 'Between 60-69.99 runs per 100 balls', 'प्रति 100 गेंदों पर 60-69.99 रन के बीच', '100 બોલમાં દીઠ 60-69.99 વચ્ચે', 'Entre 60-69,99 pistes pour 100 balles', '60-69.99 এর মধ্যে 100 বল প্রতি রান', '60-69.99 ਦੇ ਵਿਚਕਾਰ ਪ੍ਰਤੀ 100 ਗੇਂਦਾਂ ਵਿੱਚ', '100 பந்துகளுக்கு 60-69.99 ரன்கள் வரை', 'ระหว่าง 60-69.99 วิ่งต่อ 100 ลูก', -4, 0, 'STRIKE_RATE_60_6999', '', 'От 60 до 69,99 пробега на 100 мячей', 'Antara 60-69,99 lari per 100 bola', 'Sa pagitan ng 60-69.99 tumatakbo bawat 100 bola', '每 100 个球 60-69.99 次运行', '100 ಎಸೆತಗಳಿಗೆ 60-69.99 ರನ್‌ಗಳ ನಡುವೆ'),
			(17, 4, 'Below 60 runs per 100 balls', 'Below 60 runs per 100 balls', 'प्रति 100 गेंदों पर 60 रन से कम', '100 દડા દીઠ 60 રનથી નીચે', 'Moins de 60 pistes pour 100 balles', '100 বল প্রতি 60 রান নীচে', '100 ਦੌੜਾਂ ਪ੍ਰਤੀ 60 ਦੌੜਾਂ ਤੋਂ ਘੱਟ', '100 பந்துகளுக்கு 60 ரன்களுக்கு கீழே', 'ต่ำกว่า 60 วิ่งต่อ 100 ลูก', -6, 0, 'STRIKE_RATE_BELOW_60', '', 'Менее 60 пробежек на 100 мячей', 'Di bawah 60 run per 100 bola', 'Sa ibaba 60 tumatakbo bawat 100 bola', '每 100 个球 60 次以下', '100 ಎಸೆತಗಳಿಗೆ 60 ರನ್‌ಗಳ ಕೆಳಗೆ');";
    	$this->db->query($sql);	
    	
    	
		//Trasaction end
		$this->db->trans_complete();
		if ($this->db->trans_status() === FALSE )
		{
		    $this->db->trans_rollback();
		}
		else
		{
		    $this->db->trans_commit();
		}

	}

	public function down() 
	{

	}

}